// Re-export common UI primitives so modules can grab them from shared too.
export { Card, CardHeader, CardBody } from '../ui/Card'
export { Button } from '../ui/Button'
export { Badge } from '../ui/Badge'
export { ArabicTable } from './ArabicTable'
export type { Column, ArabicTableProps } from './ArabicTable'
export { StatusBadge } from './StatusBadge'
export { PageHeader } from './PageHeader'
export { KpiCard } from './KpiCard'
export type { KpiCardProps } from './KpiCard'
export { EmptyState } from './EmptyState'
export { CurrencyInput } from './CurrencyInput'
export { NumberInput, formatThousands } from './NumberInput'
export { BilingualField } from './BilingualField'
export { FormDialog } from './FormDialog'
export type { FormFieldConfig, FieldType } from './FormDialog'
export { ChartCard, CHART_COLORS, STATUS_CHART_COLORS } from './ChartCard'
export { OrgTree, buildOrgTree } from './OrgTree'
export type { OrgNode } from './OrgTree'
export { GanttList } from './GanttList'
export type { GanttTask } from './GanttList'
export { NoteWidget } from '../notes/NoteWidget'
