import { registerStrings } from '../../i18n/strings'

// Module-local strings ('accounting.*') for the Accounting module.
registerStrings({
  // Page / header
  'accounting.title': { ar: 'المحاسبة', en: 'Accounting' },
  'accounting.subtitle': {
    ar: 'القيود ودليل الحسابات والتقارير المالية',
    en: 'Journal entries, chart of accounts & financial reports',
  },

  // Tabs
  'accounting.tab.journal': { ar: 'القيود', en: 'Journal' },
  'accounting.tab.chart': { ar: 'دليل الحسابات', en: 'Chart of Accounts' },
  'accounting.tab.trial': { ar: 'ميزان المراجعة', en: 'Trial Balance' },
  'accounting.tab.vouchers': { ar: 'السندات والقيود', en: 'Vouchers & Entries' },
  'accounting.tab.parties': { ar: 'العملاء والموردون', en: 'Customers & Suppliers' },
  'accounting.tab.cash': { ar: 'الصندوق', en: 'Cash' },
  'accounting.tab.bank': { ar: 'البنوك', en: 'Banks' },

  // ---- Vouchers tab ----
  'accounting.vouchers.title': { ar: 'السندات والقيود', en: 'Vouchers & Entries' },
  'accounting.vouchers.subtitle': {
    ar: 'سندات القبض والصرف والقيود المحاسبية — كل منها يُرحّل قيداً متوازناً',
    en: 'Receipt, payment and journal vouchers — each posts a balanced entry',
  },
  'accounting.vouchers.new': { ar: 'جديد', en: 'New' },
  'accounting.vouchers.receipt': { ar: 'سند قبض', en: 'Receipt' },
  'accounting.vouchers.payment': { ar: 'سند صرف', en: 'Payment' },
  'accounting.vouchers.journal': { ar: 'قيد', en: 'Journal' },
  'accounting.vouchers.journal_count': { ar: 'عدد القيود', en: 'Journal Entries' },
  'accounting.vouchers.no_cash': { ar: 'بدون نقد', en: 'No cash' },
  'accounting.vouchers.all': { ar: 'الكل', en: 'All' },
  'accounting.vouchers.total_in': { ar: 'إجمالي المقبوضات', en: 'Total Receipts' },
  'accounting.vouchers.total_out': { ar: 'إجمالي المدفوعات', en: 'Total Payments' },
  'accounting.vouchers.net': { ar: 'صافي التدفق النقدي', en: 'Net Cash Flow' },
  'accounting.vouchers.cash_account': { ar: 'الحساب النقدي', en: 'Cash / Bank Account' },
  'accounting.vouchers.counter': { ar: 'الطرف الآخر', en: 'Counterparty' },
  'accounting.vouchers.amount': { ar: 'المبلغ', en: 'Amount' },
  'accounting.vouchers.empty': { ar: 'لا توجد حركات نقدية', en: 'No cash movements' },
  'accounting.vouchers.kind': { ar: 'النوع', en: 'Type' },

  // New voucher dialog
  'accounting.voucher.title': { ar: 'سند جديد', en: 'New Voucher' },
  'accounting.voucher.desc': { ar: 'سجّل قبض أو صرف نقدي — سيُنشأ قيد متوازن تلقائياً', en: 'Record a cash receipt or payment — a balanced entry is posted automatically' },
  'accounting.voucher.type': { ar: 'نوع السند', en: 'Voucher Type' },
  'accounting.voucher.cash_account': { ar: 'الصندوق / البنك', en: 'Cash / Bank' },
  'accounting.voucher.counter': { ar: 'الحساب المقابل', en: 'Counter Account' },
  'accounting.voucher.party': { ar: 'المستفيد / الدافع', en: 'Beneficiary / Payer' },
  'accounting.voucher.party_ph': { ar: 'اسم الجهة', en: 'Party name' },
  'accounting.voucher.amount': { ar: 'المبلغ', en: 'Amount' },
  'accounting.voucher.saved': { ar: 'تم تسجيل السند وترحيل القيد', en: 'Voucher saved and entry posted' },
  'accounting.voucher.err_fields': { ar: 'أكمل الحقول المطلوبة', en: 'Complete the required fields' },
  'accounting.voucher.err_amount': { ar: 'أدخل مبلغاً صحيحاً', en: 'Enter a valid amount' },
  'accounting.voucher.preview': { ar: 'معاينة القيد', en: 'Entry preview' },

  // ---- Parties (AR/AP) tab ----
  'accounting.parties.title': { ar: 'العملاء والموردون', en: 'Customers & Suppliers' },
  'accounting.parties.subtitle': { ar: 'أرصدة الذمم المدينة (العملاء) والذمم الدائنة (الموردون)', en: 'Receivable (customers) and payable (suppliers) balances' },
  'accounting.parties.receivables': { ar: 'الذمم المدينة — العملاء', en: 'Receivables — Customers' },
  'accounting.parties.payables': { ar: 'الذمم الدائنة — الموردون', en: 'Payables — Suppliers' },
  'accounting.parties.total_ar': { ar: 'إجمالي الذمم المدينة', en: 'Total Receivables' },
  'accounting.parties.total_ap': { ar: 'إجمالي الذمم الدائنة', en: 'Total Payables' },
  'accounting.parties.net': { ar: 'صافي المركز', en: 'Net Position' },
  'accounting.parties.balance': { ar: 'الرصيد', en: 'Balance' },
  'accounting.parties.empty': { ar: 'لا توجد أرصدة', en: 'No balances' },

  // ---- Cash & Bank tab ----
  'accounting.cash.title': { ar: 'الصندوق والبنوك', en: 'Cash & Bank' },
  'accounting.cash.subtitle': { ar: 'مراكز النقد والأرصدة البنكية والحركة الأخيرة', en: 'Cash positions, bank balances and recent movement' },
  'accounting.cash.total': { ar: 'إجمالي النقدية', en: 'Total Cash' },
  'accounting.cash.incl_advance': { ar: 'شامل السلفة التشغيلية', en: 'incl. operational advance' },
  'accounting.cash.on_hand': { ar: 'النقد في الصناديق', en: 'Cash on Hand' },
  'accounting.cash.positions': { ar: 'مراكز النقد', en: 'Cash Positions' },
  'accounting.cash.recent': { ar: 'الحركة النقدية الأخيرة', en: 'Recent Cash Movement' },
  'accounting.cash.balance_chart': { ar: 'الأرصدة حسب الحساب', en: 'Balances by Account' },
  'accounting.cash.open_ledger': { ar: 'عرض دفتر الأستاذ', en: 'View ledger' },
  'accounting.cash.in': { ar: 'وارد', en: 'In' },
  'accounting.cash.out': { ar: 'صادر', en: 'Out' },
  'accounting.cash.boxes': { ar: 'الصناديق النقدية', en: 'Cash Boxes' },
  'accounting.cash.total_iqd': { ar: 'إجمالي النقد (دينار)', en: 'Total Cash (IQD)' },
  'accounting.cash.total_usd': { ar: 'إجمالي النقد (دولار)', en: 'Total Cash (USD)' },
  'accounting.cash.current_balance': { ar: 'الرصيد الحالي', en: 'Current Balance' },
  'accounting.cash.actual_balance': { ar: 'الرصيد الفعلي', en: 'Actual Balance' },
  'accounting.cash.advance': { ar: 'السلفة التشغيلية', en: 'Operational Advance' },
  'accounting.cash.main_actual': { ar: 'الرصيد الفعلي للصناديق', en: 'Cash — Actual' },
  'accounting.cash.add_box': { ar: 'إضافة صندوق', en: 'Add cash box' },

  // ---- Bank management ----
  'accounting.bank.management': { ar: 'إدارة البنوك', en: 'Bank Management' },
  'accounting.bank.new': { ar: 'بنك جديد', en: 'New Bank' },
  'accounting.bank.edit': { ar: 'تعديل البنك', en: 'Edit Bank' },
  'accounting.bank.desc': { ar: 'بيانات البنك والأرصدة الافتتاحية بالدينار والدولار', en: 'Bank details and opening balances in IQD and USD' },
  'accounting.bank.name': { ar: 'اسم البنك', en: 'Bank Name' },
  'accounting.bank.name_ar': { ar: 'الاسم بالعربية', en: 'Name (Arabic)' },
  'accounting.bank.name_en': { ar: 'الاسم بالإنجليزية', en: 'Name (English)' },
  'accounting.bank.account_number': { ar: 'رقم الحساب', en: 'Account No.' },
  'accounting.bank.branch': { ar: 'الفرع', en: 'Branch' },
  'accounting.bank.opening_iqd': { ar: 'الرصيد الافتتاحي (دينار)', en: 'Opening Balance (IQD)' },
  'accounting.bank.opening_usd': { ar: 'الرصيد الافتتاحي (دولار)', en: 'Opening Balance (USD)' },
  'accounting.bank.balance_iqd': { ar: 'الرصيد (دينار)', en: 'Balance (IQD)' },
  'accounting.bank.balance_usd': { ar: 'الرصيد (دولار)', en: 'Balance (USD)' },
  'accounting.bank.total_iqd': { ar: 'إجمالي أرصدة البنوك (دينار)', en: 'Total Bank (IQD)' },
  'accounting.bank.total_usd': { ar: 'إجمالي أرصدة البنوك (دولار)', en: 'Total Bank (USD)' },
  'accounting.bank.empty': { ar: 'لا توجد بنوك', en: 'No banks' },
  'accounting.bank.empty_hint': { ar: 'أضف بنكاً جديداً لإدارة أرصدته', en: 'Add a bank to manage its balances' },
  'accounting.bank.confirm_delete': { ar: 'هل أنت متأكد من حذف هذا البنك؟', en: 'Are you sure you want to delete this bank?' },
  'accounting.bank.err_name': { ar: 'يرجى إدخال اسم البنك', en: 'Please enter the bank name' },

  // Toolbar / filters
  'accounting.filter.from': { ar: 'من تاريخ', en: 'From' },
  'accounting.filter.to': { ar: 'إلى تاريخ', en: 'To' },
  'accounting.filter.range': { ar: 'الفترة', en: 'Period' },
  'accounting.filter.all_companies': { ar: 'كل الشركات', en: 'All companies' },
  'accounting.filter.scope_hint': {
    ar: 'يتم احترام فلتر الشركة العام من الشريط العلوي',
    en: 'Respects the global company filter in the top bar',
  },

  // Journal list
  'accounting.journal.title': { ar: 'دفتر اليومية', en: 'General Journal' },
  'accounting.journal.new': { ar: 'قيد جديد', en: 'New Entry' },
  'accounting.journal.serial': { ar: 'التسلسل', en: 'Serial' },
  'accounting.journal.doc': { ar: 'رقم المستند', en: 'Doc No.' },
  'accounting.journal.date': { ar: 'التاريخ', en: 'Date' },
  'accounting.journal.desc': { ar: 'البيان', en: 'Description' },
  'accounting.journal.debit': { ar: 'مدين', en: 'Debit' },
  'accounting.journal.credit': { ar: 'دائن', en: 'Credit' },
  'accounting.journal.remaining': { ar: 'المتبقي في الصندوق', en: 'Cash Box Balance' },
  'accounting.journal.receipt_iqd': { ar: 'قبض دينار', en: 'Receipt IQD' },
  'accounting.journal.receipt_usd': { ar: 'قبض دولار', en: 'Receipt USD' },
  'accounting.journal.payment_iqd': { ar: 'صرف دينار', en: 'Payment IQD' },
  'accounting.journal.payment_usd': { ar: 'صرف دولار', en: 'Payment USD' },
  'accounting.journal.balance_iqd': { ar: 'الرصيد دينار', en: 'Balance IQD' },
  'accounting.journal.balance_usd': { ar: 'الرصيد دولار', en: 'Balance USD' },
  'accounting.journal.total_iqd': { ar: 'إجمالي الدينار', en: 'Total IQD' },
  'accounting.journal.total_usd': { ar: 'إجمالي الدولار', en: 'Total USD' },
  'accounting.journal.status': { ar: 'الحالة', en: 'Status' },
  'accounting.journal.empty': { ar: 'لا توجد قيود', en: 'No journal entries' },
  'accounting.journal.empty_hint': {
    ar: 'ابدأ بإنشاء قيد محاسبي جديد',
    en: 'Start by creating a new journal entry',
  },
  'accounting.journal.count': { ar: 'قيد', en: 'entries' },
  'accounting.journal.search_ph': { ar: 'بحث بالرقم أو البيان أو الاسم...', en: 'Search by number, description or name...' },
  'accounting.journal.all_projects': { ar: 'كل المشاريع', en: 'All projects' },
  'accounting.journal.all_accounts': { ar: 'كل الحسابات', en: 'All accounts' },
  'accounting.journal.all_banks': { ar: 'كل المصارف', en: 'All banks' },
  'accounting.journal.clear_filters': { ar: 'مسح الفلاتر', en: 'Clear filters' },

  // Entry view dialog
  'accounting.entry.title': { ar: 'تفاصيل القيد', en: 'Entry Details' },
  'accounting.entry.account': { ar: 'الحساب', en: 'Account' },
  'accounting.entry.lines': { ar: 'سطور القيد', en: 'Entry Lines' },
  'accounting.entry.company': { ar: 'الشركة', en: 'Company' },
  'accounting.entry.project': { ar: 'المشروع', en: 'Project' },
  'accounting.entry.currency': { ar: 'العملة', en: 'Currency' },

  // New entry dialog
  'accounting.new.title': { ar: 'قيد محاسبي جديد', en: 'New Journal Entry' },
  'accounting.new.desc': {
    ar: 'أدخل بيانات القيد وسطور الطرفين المدين والدائن',
    en: 'Enter the entry header and its debit/credit lines',
  },
  // Access control / read-only
  'accounting.readonly.badge': { ar: 'قراءة فقط', en: 'Read-only' },
  'accounting.readonly.title': { ar: 'وضع القراءة فقط', en: 'Read-only mode' },
  'accounting.readonly.hint': {
    ar: 'التعديل في المحاسبة متاح لدور «المحاسب» فقط. بدّل الدور من القائمة العلوية للتعديل.',
    en: 'Editing in Accounting is limited to the “Accountant” role. Switch role from the top menu to edit.',
  },

  // Approval (معتمد / غير معتمد)
  'accounting.approve.approve': { ar: 'اعتماد القيد', en: 'Approve' },
  'accounting.approve.unapprove': { ar: 'إلغاء الاعتماد', en: 'Unapprove' },
  'accounting.approve.approved': { ar: 'تم اعتماد القيد', en: 'Entry approved' },
  'accounting.approve.unapproved': { ar: 'تم إلغاء الاعتماد', en: 'Entry set to unapproved' },
  'accounting.approve.status': { ar: 'حالة القيد', en: 'Entry status' },
  'accounting.approve.opt_approved': { ar: 'معتمد', en: 'Approved' },
  'accounting.approve.opt_draft': { ar: 'غير معتمد', en: 'Unapproved' },
  'accounting.approve.tooltip_approve': { ar: 'اعتماد', en: 'Approve' },
  'accounting.approve.tooltip_unapprove': { ar: 'إلغاء الاعتماد', en: 'Unapprove' },

  // Edit / locked
  'accounting.edit.title': { ar: 'تعديل القيد', en: 'Edit Entry' },
  'accounting.edit.desc': {
    ar: 'عدّل بيانات القيد وسطوره. لاعتماده غيّر الحالة إلى «معتمد» — وبعد الاعتماد يُقفل ولا يمكن تعديله.',
    en: 'Edit the entry header and lines. Set status to “Approved” to post it — once approved it is locked.',
  },
  'accounting.locked.hint': { ar: 'قيد معتمد ومقفل — لا يمكن تعديله', en: 'Approved & locked — cannot be edited' },
  'accounting.edit.delete': { ar: 'حذف القيد', en: 'Delete entry' },
  'accounting.edit.confirm_delete': {
    ar: 'سيُحذف هذا القيد وكل سطوره نهائياً. هل أنت متأكد؟',
    en: 'This entry and all its lines will be permanently deleted. Are you sure?',
  },
  'accounting.edit.deleted': { ar: 'تم حذف القيد', en: 'Entry deleted' },
  'accounting.edit.deleting': { ar: 'جارٍ الحذف...', en: 'Deleting...' },

  'accounting.new.header': { ar: 'بيانات القيد', en: 'Entry Header' },
  'accounting.new.company': { ar: 'الشركة', en: 'Company' },
  'accounting.new.project': { ar: 'المشروع (اختياري)', en: 'Project (optional)' },
  'accounting.new.no_project': { ar: 'بدون مشروع', en: 'No project' },
  'accounting.new.general_project': { ar: 'عام', en: 'General' },
  'accounting.new.date': { ar: 'التاريخ', en: 'Date' },
  'accounting.new.serial_number': { ar: 'التسلسل', en: 'Serial No.' },
  'accounting.new.serial_number_ph': { ar: 'تلقائي إن تُرك فارغاً', en: 'Auto if left blank' },
  'accounting.new.serial_number_hint': { ar: 'يُولّد تلقائياً عند تركه فارغاً', en: 'Generated automatically when left empty' },
  'accounting.new.doc_number': { ar: 'رقم المستند', en: 'Document No.' },
  'accounting.new.doc_number_ph': { ar: 'أدخل رقم المستند يدوياً', en: 'Enter document number manually' },
  'accounting.new.doc_number_hint': { ar: 'الترقيم يدوي — هذا الرقم هو رقم القيد', en: 'Manual numbering — this is the entry number' },
  'accounting.new.err_doc': { ar: 'يرجى إدخال رقم المستند', en: 'Please enter the document number' },
  'accounting.new.currency': { ar: 'العملة', en: 'Currency' },
  'accounting.new.exchange_rate': { ar: 'سعر الصرف', en: 'Exchange Rate' },
  'accounting.new.currency_rate': { ar: 'سعر العملة', en: 'Rate' },
  'accounting.new.exchange_rate_hint': { ar: '1 {from} = ? {to}', en: '1 {from} = ? {to}' },
  'accounting.new.converted': { ar: 'القيمة المحوّلة', en: 'Converted value' },
  'accounting.new.description': { ar: 'البيان', en: 'Description' },
  'accounting.new.description_ph': {
    ar: 'مثال: إثبات مصروف وقود للمشروع',
    en: 'e.g. Record fuel expense for the project',
  },
  'accounting.new.lines': { ar: 'سطور القيد', en: 'Entry Lines' },
  'accounting.new.line_account': { ar: 'الحساب', en: 'Account' },
  'accounting.new.line_account_ph': { ar: 'اختر الحساب', en: 'Select account' },
  'accounting.new.line_debit': { ar: 'مدين', en: 'Debit' },
  'accounting.new.line_credit': { ar: 'دائن', en: 'Credit' },
  'accounting.new.line_desc': { ar: 'بيان السطر', en: 'Line note' },
  'accounting.new.add_line': { ar: 'إضافة سطر', en: 'Add line' },
  'accounting.new.remove_line': { ar: 'حذف السطر', en: 'Remove line' },
  'accounting.new.total_debit': { ar: 'إجمالي المدين', en: 'Total Debit' },
  'accounting.new.total_credit': { ar: 'إجمالي الدائن', en: 'Total Credit' },
  'accounting.new.diff': { ar: 'الفرق', en: 'Difference' },
  'accounting.new.balanced': { ar: 'القيد متوازن', en: 'Entry is balanced' },
  'accounting.new.unbalanced': { ar: 'القيد غير متوازن', en: 'Entry is not balanced' },
  'accounting.new.submit': { ar: 'ترحيل القيد', en: 'Post Entry' },
  'accounting.new.saving': { ar: 'جارٍ الترحيل...', en: 'Posting...' },
  'accounting.new.saved': { ar: 'تم ترحيل القيد بنجاح', en: 'Entry posted successfully' },
  'accounting.new.err_company': { ar: 'يرجى اختيار الشركة', en: 'Please select a company' },
  'accounting.new.err_lines': {
    ar: 'يجب إدخال سطرين على الأقل بقيم صحيحة',
    en: 'At least two valid lines are required',
  },
  'accounting.new.err_account': { ar: 'يرجى اختيار حساب لكل سطر', en: 'Select an account for every line' },
  'accounting.new.err_balance': {
    ar: 'يجب أن يتساوى إجمالي المدين مع إجمالي الدائن',
    en: 'Total debit must equal total credit',
  },

  // Chart of accounts
  'accounting.chart.title': { ar: 'دليل الحسابات', en: 'Chart of Accounts' },
  'accounting.chart.subtitle': {
    ar: 'الشجرة الهرمية للحسابات حسب التصنيف',
    en: 'Hierarchical account tree grouped by class',
  },
  'accounting.chart.code': { ar: 'رمز الحساب', en: 'Code' },
  'accounting.chart.name': { ar: 'اسم الحساب', en: 'Account Name' },
  'accounting.chart.type': { ar: 'التصنيف', en: 'Type' },
  'accounting.chart.posting': { ar: 'حساب ترحيل', en: 'Posting' },
  'accounting.chart.parent': { ar: 'حساب رئيسي', en: 'Header' },

  // ---- Editable tree: add ----
  'accounting.add.title': { ar: 'إضافة حساب جديد', en: 'Add New Account' },
  'accounting.add.child': { ar: 'إضافة حساب فرعي', en: 'Add Sub-account' },
  'accounting.add.button': { ar: 'إضافة الحساب', en: 'Add account' },
  'accounting.add.tooltip': { ar: 'إضافة حساب', en: 'Add account' },
  'accounting.add.child_tooltip': { ar: 'إضافة حساب فرعي', en: 'Add sub-account' },
  'accounting.add.code': { ar: 'رمز الحساب', en: 'Account code' },
  'accounting.add.name_ar': { ar: 'الاسم بالعربية', en: 'Name (Arabic)' },
  'accounting.add.name_en': { ar: 'الاسم بالإنجليزية', en: 'Name (English)' },
  'accounting.add.type': { ar: 'التصنيف', en: 'Type' },
  'accounting.add.parent': { ar: 'الحساب الرئيسي', en: 'Parent account' },
  'accounting.add.parent_none': { ar: 'بدون (حساب رئيسي أعلى)', en: 'None (top level)' },
  'accounting.add.kind': { ar: 'نوع الحساب', en: 'Kind' },
  'accounting.add.posting': { ar: 'حساب ترحيل (يقبل القيود)', en: 'Posting (accepts entries)' },
  'accounting.add.header': { ar: 'حساب رئيسي (تجميعي)', en: 'Header (grouping)' },
  'accounting.add.err_dup': { ar: 'رمز الحساب مستخدم مسبقاً', en: 'Account code already exists' },

  // ---- Editable tree: delete (soft / archive) ----
  'accounting.del.tooltip': { ar: 'حذف الحساب', en: 'Delete account' },
  'accounting.del.title': { ar: 'حذف حساب', en: 'Delete Account' },
  'accounting.del.blocked_title': { ar: 'لا يمكن الحذف', en: 'Cannot delete' },
  'accounting.del.blocked': {
    ar: 'هذا الحساب يحتوي على حسابات فرعية. احذف الحسابات الفرعية أولاً ثم احذفه.',
    en: 'This account has sub-accounts. Remove the sub-accounts first.',
  },
  'accounting.del.warn_title': { ar: '⚠️ تنبيه: قد تحذف شيئاً مهماً', en: '⚠️ Warning: you may be removing something important' },
  'accounting.del.warn_file': { ar: 'هذا الحساب يحتوي على حركات محاسبية مرتبطة به:', en: 'This account has accounting records linked to it:' },
  'accounting.del.movements': { ar: 'حركة', en: 'records' },
  'accounting.del.soft': {
    ar: 'لن يُحذف الحساب فعلياً من قاعدة البيانات — سيتم أرشفته وإخفاؤه فقط، مع الاحتفاظ بكل سجلاته.',
    en: 'The account will NOT be deleted from the database — it is archived and hidden, with all its records preserved.',
  },
  'accounting.del.confirm_empty': { ar: 'هل تريد أرشفة هذا الحساب وإخفاءه؟', en: 'Archive and hide this account?' },
  'accounting.del.action': { ar: 'أرشفة وإخفاء', en: 'Archive & hide' },
  'accounting.del.done': { ar: 'تم أرشفة الحساب وإخفاؤه', en: 'Account archived and hidden' },
  'accounting.chart.rename': { ar: 'إعادة تسمية', en: 'Rename' },
  'accounting.chart.expand_all': { ar: 'توسيع الكل', en: 'Expand all' },
  'accounting.chart.collapse_all': { ar: 'طي الكل', en: 'Collapse all' },
  'accounting.chart.count': { ar: 'حساب', en: 'accounts' },
  'accounting.chart.posting_count': { ar: 'حساب ترحيل', en: 'posting accounts' },

  // ---- Account detail page ----
  'accounting.account.back': { ar: 'رجوع إلى دليل الحسابات', en: 'Back to Chart of Accounts' },
  'accounting.account.open': { ar: 'فتح الحساب', en: 'Open account' },
  'accounting.account.not_found': { ar: 'الحساب غير موجود', en: 'Account not found' },
  'accounting.account.info': { ar: 'معلومات الحساب', en: 'Account Information' },
  'accounting.account.kind': { ar: 'نوع الحساب', en: 'Kind' },
  'accounting.account.posting': { ar: 'حساب ترحيل', en: 'Posting' },
  'accounting.account.header': { ar: 'حساب رئيسي', en: 'Header' },
  'accounting.account.level': { ar: 'المستوى', en: 'Level' },
  'accounting.account.parent': { ar: 'الحساب الرئيسي', en: 'Parent Account' },
  'accounting.account.normal_balance': { ar: 'طبيعة الرصيد', en: 'Normal Balance' },
  'accounting.account.debit_nature': { ar: 'مدين', en: 'Debit' },
  'accounting.account.credit_nature': { ar: 'دائن', en: 'Credit' },
  'accounting.account.debit_short': { ar: 'مدين', en: 'Dr' },
  'accounting.account.credit_short': { ar: 'دائن', en: 'Cr' },
  'accounting.account.total_debit': { ar: 'إجمالي المدين', en: 'Total Debit' },
  'accounting.account.total_credit': { ar: 'إجمالي الدائن', en: 'Total Credit' },
  'accounting.account.balance': { ar: 'الرصيد', en: 'Balance' },
  'accounting.account.net_balance': { ar: 'الرصيد (مدين − دائن)', en: 'Net Balance (Dr − Cr)' },
  'accounting.account.balance_iqd': { ar: 'الرصيد بالدينار', en: 'Balance (IQD)' },
  'accounting.account.balance_usd': { ar: 'الرصيد بالدولار', en: 'Balance (USD)' },
  'accounting.account.sub_accounts': { ar: 'الحسابات الفرعية', en: 'Sub-accounts' },
  'accounting.account.sub_count': { ar: 'حساب فرعي', en: 'sub-accounts' },
  'accounting.account.txn_count': { ar: 'حركة', en: 'transactions' },
  'accounting.account.children_hint': {
    ar: 'الحسابات المندرجة تحت هذا الحساب — اضغط للفتح والتنقل',
    en: 'Accounts grouped under this account — click to drill in',
  },
  'accounting.account.ledger': { ar: 'دفتر أستاذ الحساب', en: 'Account Ledger' },
  'accounting.account.ledger_hint': {
    ar: 'الحركة التفصيلية على هذا الحساب مع الرصيد الجاري',
    en: 'Detailed movement on this account with running balance',
  },

  // Account types
  'accounting.type.ASSET': { ar: 'أصول', en: 'Assets' },
  'accounting.type.LIABILITY': { ar: 'خصوم', en: 'Liabilities' },
  'accounting.type.EQUITY': { ar: 'حقوق ملكية', en: 'Equity' },
  'accounting.type.REVENUE': { ar: 'إيرادات', en: 'Revenue' },
  'accounting.type.EXPENSE': { ar: 'مصروفات', en: 'Expenses' },

  // Trial balance
  'accounting.trial.title': { ar: 'ميزان المراجعة', en: 'Trial Balance' },
  'accounting.trial.subtitle': {
    ar: 'أرصدة الحسابات المدينة والدائنة',
    en: 'Debit and credit balances by account',
  },
  'accounting.trial.code': { ar: 'الرمز', en: 'Code' },
  'accounting.trial.name': { ar: 'الحساب', en: 'Account' },
  'accounting.trial.debit': { ar: 'مدين', en: 'Debit' },
  'accounting.trial.credit': { ar: 'دائن', en: 'Credit' },
  'accounting.trial.balance': { ar: 'الرصيد', en: 'Balance' },
  'accounting.trial.totals': { ar: 'الإجمالي', en: 'Totals' },
  'accounting.trial.balanced': { ar: 'متوازن', en: 'Balanced' },
  'accounting.trial.unbalanced': { ar: 'غير متوازن', en: 'Out of balance' },
  'accounting.trial.empty': { ar: 'لا توجد أرصدة', en: 'No balances' },

  // Income statement
  'accounting.income.title': { ar: 'قائمة الدخل', en: 'Income Statement' },
  'accounting.income.subtitle': {
    ar: 'الإيرادات والمصروفات وصافي الربح للفترة',
    en: 'Revenue, expenses and net profit for the period',
  },
  'accounting.income.revenue': { ar: 'الإيرادات', en: 'Revenue' },
  'accounting.income.expense': { ar: 'المصروفات', en: 'Expenses' },
  'accounting.income.total_revenue': { ar: 'إجمالي الإيرادات', en: 'Total Revenue' },
  'accounting.income.total_expense': { ar: 'إجمالي المصروفات', en: 'Total Expenses' },
  'accounting.income.net_profit': { ar: 'صافي الربح', en: 'Net Profit' },
  'accounting.income.net_loss': { ar: 'صافي الخسارة', en: 'Net Loss' },
  'accounting.income.empty': { ar: 'لا توجد بيانات لعرضها', en: 'No data to display' },

  // Balance sheet
  'accounting.balance.title': { ar: 'الميزانية العمومية', en: 'Balance Sheet' },
  'accounting.balance.subtitle': {
    ar: 'الأصول مقابل الخصوم وحقوق الملكية',
    en: 'Assets versus liabilities & equity',
  },
  'accounting.balance.assets': { ar: 'الأصول', en: 'Assets' },
  'accounting.balance.liabilities': { ar: 'الخصوم', en: 'Liabilities' },
  'accounting.balance.equity': { ar: 'حقوق الملكية', en: 'Equity' },
  'accounting.balance.net_profit': { ar: 'صافي ربح الفترة', en: 'Net profit for the period' },
  'accounting.balance.total_assets': { ar: 'إجمالي الأصول', en: 'Total Assets' },
  'accounting.balance.total_le': {
    ar: 'إجمالي الخصوم وحقوق الملكية',
    en: 'Total Liabilities & Equity',
  },
  'accounting.balance.balanced': { ar: 'الميزانية متوازنة', en: 'Balance sheet is balanced' },
  'accounting.balance.unbalanced': { ar: 'الميزانية غير متوازنة', en: 'Balance sheet is out of balance' },

  // Reports
  'accounting.reports.title': { ar: 'التقارير المالية', en: 'Financial Reports' },
  'accounting.reports.subtitle': {
    ar: 'دفتر الأستاذ وتقارير الأرباح والخسائر',
    en: 'General ledger and profit & loss reports',
  },
  'accounting.reports.ledger': { ar: 'دفتر الأستاذ العام', en: 'General Ledger' },
  'accounting.reports.ledger_hint': {
    ar: 'اختر حساباً لعرض حركته والرصيد الجاري',
    en: 'Select an account to view its movements and running balance',
  },
  'accounting.reports.select_account': { ar: 'اختر الحساب', en: 'Select an account' },
  'accounting.reports.company_pnl': { ar: 'أرباح وخسائر الشركة', en: 'Company P&L' },
  'accounting.reports.project_pnl': { ar: 'أرباح وخسائر المشروع', en: 'Project P&L' },
  'accounting.reports.select_project': { ar: 'اختر المشروع', en: 'Select a project' },
  'accounting.reports.revenue': { ar: 'الإيرادات', en: 'Revenue' },
  'accounting.reports.expense': { ar: 'المصروفات', en: 'Expenses' },
  'accounting.reports.net': { ar: 'صافي الربح', en: 'Net Profit' },
  'accounting.reports.ledger_date': { ar: 'التاريخ', en: 'Date' },
  'accounting.reports.ledger_doc': { ar: 'المستند', en: 'Doc' },
  'accounting.reports.ledger_desc': { ar: 'البيان', en: 'Description' },
  'accounting.reports.ledger_debit': { ar: 'مدين', en: 'Debit' },
  'accounting.reports.ledger_credit': { ar: 'دائن', en: 'Credit' },
  'accounting.reports.ledger_balance': { ar: 'الرصيد الجاري', en: 'Running Balance' },
  'accounting.reports.ledger_empty': { ar: 'لا توجد حركة على هذا الحساب', en: 'No movement on this account' },
  'accounting.reports.pick_first': {
    ar: 'اختر حساباً من القائمة لعرض دفتر الأستاذ',
    en: 'Pick an account above to view the ledger',
  },
})
