// AUTO-GENERATED mapping of warehouse item codes to the taxonomy in warehouseTaxonomy.ts.
// Produced by the warehouse-classification workflow (12 classifier + 12 adversarial
// verifier agents over the real Abu Ghraib / Al Dora inventory). Do not hand-edit
// wholesale — individual corrections are fine.
// Tuple: [category, sub_category, size_label, size_mm]
export type ItemClass = [string, string | null, string | null, number | null]

export const ITEM_CLASSIFICATION: Record<string, ItemClass> = {
  'ITM-AD-001': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-002': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-003': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AD-004': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AD-005': ['EQUIPMENT', 'GENERATORS', null, null],
  'ITM-AD-006': ['EQUIPMENT', 'GENERATORS', null, null],
  'ITM-AD-007': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-008': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AD-009': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AD-010': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-011': ['FINISHING', 'PAINTS', null, null],
  'ITM-AD-012': ['PUMPS', 'SUBMERSIBLES', null, null],
  'ITM-AD-013': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-014': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-015': ['SITE', 'CABINS', null, null],
  'ITM-AD-016': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AD-017': ['FITTINGS', 'FITTINGS_MISC', 'DN 900', 900],
  'ITM-AD-018': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-019': ['SITE', 'CABINS', null, null],
  'ITM-AD-020': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-021': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-022': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-023': ['FINISHING', 'TILES', null, null],
  'ITM-AD-024': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-025': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-026': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AD-027': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AD-028': ['SAFETY', null, null, null],
  'ITM-AD-029': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AD-030': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-031': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-032': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-033': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AD-034': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AD-035': ['SANITARY', null, null, null],
  'ITM-AD-036': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-037': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-038': ['PIPES', 'STEEL_PIPES', null, null],
  'ITM-AD-039': ['PUMPS', 'PUMPS_MOTORS', null, null],
  'ITM-AD-040': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-041': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-042': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-043': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-044': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-045': ['PUMPS', 'PUMPS_MOTORS', null, null],
  'ITM-AD-046': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-047': ['FITTINGS', 'GASKETS', 'DN 900', 900],
  'ITM-AD-048': ['SCAFFOLDING', 'SCAFFOLD_CLAMPS', null, null],
  'ITM-AD-049': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-050': ['SAFETY', null, null, null],
  'ITM-AD-051': ['OTHER', null, null, null],
  'ITM-AD-052': ['OTHER', null, null, null],
  'ITM-AD-053': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-054': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-055': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-056': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AD-058': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-059': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-060': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-061': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-062': ['FINISHING', 'PAINTS', null, null],
  'ITM-AD-063': ['FINISHING', 'PAINTS', null, null],
  'ITM-AD-064': ['PUMPS', 'HOSES', '2 انج', 50.8],
  'ITM-AD-066': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-067': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-068': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-069': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-070': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-071': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-072': ['PUMPS', 'PUMPS_MOTORS', null, null],
  'ITM-AD-073': ['EQUIPMENT', 'GENERATORS', null, null],
  'ITM-AD-074': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-075': ['PUMPS', 'SUBMERSIBLES', null, null],
  'ITM-AD-076': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AD-077': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-078': ['PUMPS', 'HOSES', '2 انج', 50.8],
  'ITM-AD-079': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-080': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-081': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-082': ['SANITARY', null, null, null],
  'ITM-AD-083': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-084': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-085': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AD-086': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-087': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-088': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-089': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-090': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-091': ['FITTINGS', 'BENDS', '4 انج', 101.6],
  'ITM-AD-092': ['FITTINGS', 'FITTINGS_MISC', '4 انج', 101.6],
  'ITM-AD-093': ['FITTINGS', 'FITTINGS_MISC', '2 انج', 50.8],
  'ITM-AD-094': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-095': ['PIPES', 'STEEL_PIPES', '1 انج', 25.4],
  'ITM-AD-096': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-097': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-098': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-099': ['PUMPS', 'PUMPS_MOTORS', null, null],
  'ITM-AD-100': ['FITTINGS', 'COUPLINGS', 'DN 600', 600],
  'ITM-AD-101': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-102': ['VALVES', 'GATE_VALVES', 'DN 300', 300],
  'ITM-AD-103': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-104': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-105': ['CONSTRUCTION', 'TIMBER', null, null],
  'ITM-AD-106': ['FITTINGS', 'FITTINGS_MISC', null, null],
  'ITM-AD-107': ['FINISHING', 'PAINTS', null, null],
  'ITM-AD-108': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-109': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-110': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-111': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AD-112': ['FITTINGS', 'FLANGES', 'DN 400', 400],
  'ITM-AD-113': ['FINISHING', 'TILES', null, null],
  'ITM-AD-114': ['FITTINGS', 'COUPLINGS', 'DN 300', 300],
  'ITM-AD-115': ['FITTINGS', 'FLANGES', 'DN 1000', 1000],
  'ITM-AD-116': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-117': ['FINISHING', 'PAINTS', null, null],
  'ITM-AD-118': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-119': ['FITTINGS', 'GASKETS', 'DN 900', 900],
  'ITM-AD-120': ['FITTINGS', 'GASKETS', 'DN 100', 100],
  'ITM-AD-121': ['FITTINGS', 'GASKETS', 'DN 200', 200],
  'ITM-AD-122': ['FITTINGS', 'GASKETS', 'DN 300', 300],
  'ITM-AD-123': ['FITTINGS', 'GASKETS', 'DN 500', 500],
  'ITM-AD-124': ['FITTINGS', 'GASKETS', 'DN 600', 600],
  'ITM-AD-125': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-126': ['FINISHING', 'TILES', null, null],
  'ITM-AD-127': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-128': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-129': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-130': ['FINISHING', 'TILES', null, null],
  'ITM-AD-131': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-132': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-133': ['SANITARY', null, null, null],
  'ITM-AD-134': ['SANITARY', null, null, null],
  'ITM-AD-135': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-136': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-137': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-138': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-140': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AD-141': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AD-142': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AD-143': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-144': ['OTHER', null, null, null],
  'ITM-AD-145': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-146': ['SITE', 'CABINS', null, null],
  'ITM-AD-147': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-148': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-149': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-150': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-151': ['SITE', 'CABINS', null, null],
  'ITM-AD-152': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-153': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-154': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-155': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-163': ['SAFETY', null, null, null],
  'ITM-AD-164': ['SAFETY', null, null, null],
  'ITM-AD-166': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AD-167': ['PUMPS', 'HOSES', null, null],
  'ITM-AD-168': ['SAFETY', null, null, null],
  'ITM-AD-171': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-172': ['SAFETY', null, null, null],
  'ITM-AD-173': ['SAFETY', null, null, null],
  'ITM-AD-174': ['SAFETY', null, null, null],
  'ITM-AD-176': ['SAFETY', null, null, null],
  'ITM-AD-178': ['FINISHING', 'PAINTS', null, null],
  'ITM-AD-179': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-180': ['FINISHING', 'INSULATION', null, null],
  'ITM-AD-182': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AD-184': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-185': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-186': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-187': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-188': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-189': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-190': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-191': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-192': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AD-193': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-194': ['OTHER', null, null, null],
  'ITM-AD-195': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-196': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-197': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-198': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-200': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-201': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-202': ['OTHER', null, null, null],
  'ITM-AD-204': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-205': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AD-206': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-207': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AD-208': ['SANITARY', null, null, null],
  'ITM-AD-209': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-211': ['PUMPS', 'SUBMERSIBLES', null, null],
  'ITM-AD-212': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AD-213': ['PUMPS', 'SUBMERSIBLES', null, null],
  'ITM-AD-214': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-215': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AD-216': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AD-217': ['CONSTRUCTION', 'CEMENT_AGGREGATES', null, null],
  'ITM-AD-218': ['FITTINGS', 'FITTINGS_MISC', '4 انج', 101.6],
  'ITM-AD-219': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-220': ['SANITARY', null, null, null],
  'ITM-AD-221': ['PUMPS', 'HOSES', '1 انج', 25.4],
  'ITM-AD-222': ['PUMPS', 'HOSES', '4 انج', 101.6],
  'ITM-AD-223': ['PUMPS', 'HOSES', '3 انج', 76.2],
  'ITM-AD-224': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-225': ['PUMPS', 'HOSES', '3 انج', 76.2],
  'ITM-AD-226': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AD-227': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-228': ['PUMPS', 'HOSES', null, null],
  'ITM-AD-229': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-231': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-232': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-233': ['OTHER', null, null, null],
  'ITM-AD-234': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-235': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-236': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-237': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-238': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-239': ['FINISHING', 'PAINTS', null, null],
  'ITM-AD-240': ['FINISHING', 'PAINTS', null, null],
  'ITM-AD-241': ['FINISHING', 'PAINTS', null, null],
  'ITM-AD-242': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-243': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-244': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AD-245': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-246': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-247': ['PIPES', 'PLASTIC_PIPES', null, null],
  'ITM-AD-248': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-249': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-250': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-251': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-252': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-253': ['SAFETY', null, null, null],
  'ITM-AD-254': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-255': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-256': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-257': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-258': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-259': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AD-260': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-261': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-263': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-264': ['OTHER', null, null, null],
  'ITM-AD-265': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-266': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-267': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-268': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-269': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-270': ['PIPES', 'STEEL_PIPES', '3 انج', 76.2],
  'ITM-AD-271': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-273': ['FINISHING', 'INSULATION', null, null],
  'ITM-AD-274': ['FINISHING', 'INSULATION', null, null],
  'ITM-AD-275': ['FINISHING', 'INSULATION', null, null],
  'ITM-AD-276': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-277': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-278': ['SAFETY', null, null, null],
  'ITM-AD-279': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-280': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-281': ['FINISHING', 'INSULATION', null, null],
  'ITM-AD-282': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-283': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-284': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-285': ['FITTINGS', 'GASKETS', null, null],
  'ITM-AD-286': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-287': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-288': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-289': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-290': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-291': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AD-294': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AD-295': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AD-296': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-297': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-298': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-299': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AD-300': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-301': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-302': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-303': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-304': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-305': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-306': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AD-307': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-308': ['PUMPS', 'SUBMERSIBLES', null, null],
  'ITM-AD-309': ['PUMPS', 'PUMPS_MOTORS', null, null],
  'ITM-AD-310': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-311': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AD-312': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-313': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AD-314': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-316': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AD-317': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-318': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-320': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-321': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AD-322': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-323': ['PUMPS', 'PUMPS_MOTORS', null, null],
  'ITM-AD-324': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-325': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AD-326': ['PUMPS', 'PUMPS_MOTORS', null, null],
  'ITM-AD-327': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-328': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AD-329': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-331': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-332': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-335': ['VALVES', 'GATE_VALVES', 'DN 150', 150],
  'ITM-AD-336': ['VALVES', 'GATE_VALVES', 'DN 100', 100],
  'ITM-AD-337': ['FITTINGS', 'BENDS', 'DN 150', 150],
  'ITM-AD-338': ['FITTINGS', 'FITTINGS_MISC', null, null],
  'ITM-AD-339': ['FITTINGS', 'FITTINGS_MISC', 'DN 80', 80],
  'ITM-AD-340': ['FITTINGS', 'BENDS', 'DN 80', 80],
  'ITM-AD-341': ['FITTINGS', 'COUPLINGS', 'DN 100', 100],
  'ITM-AD-342': ['FITTINGS', 'BENDS', 'DN 150', 150],
  'ITM-AD-343': ['FITTINGS', 'REDUCERS', null, null],
  'ITM-AD-344': ['FITTINGS', 'REDUCERS', null, null],
  'ITM-AD-345': ['FITTINGS', 'REDUCERS', null, null],
  'ITM-AD-346': ['FITTINGS', 'REDUCERS', null, null],
  'ITM-AD-349': ['FITTINGS', 'FLANGES', 'DN 600', 600],
  'ITM-AD-350': ['FITTINGS', 'FLANGES', 'DN 400', 400],
  'ITM-AD-351': ['FITTINGS', 'FLANGES', 'DN 500', 500],
  'ITM-AD-352': ['FITTINGS', 'FLANGES', 'DN 500', 500],
  'ITM-AD-353': ['FITTINGS', 'FLANGES', 'DN 450', 450],
  'ITM-AD-354': ['FITTINGS', 'FLANGES', 'DN 300', 300],
  'ITM-AD-355': ['FITTINGS', 'FLANGES', 'DN 150', 150],
  'ITM-AD-356': ['FITTINGS', 'FLANGES', 'DN 100', 100],
  'ITM-AD-357': ['FITTINGS', 'FLANGES', 'DN 100', 100],
  'ITM-AD-358': ['FITTINGS', 'COUPLINGS', 'DN 500', 500],
  'ITM-AD-360': ['FITTINGS', 'REDUCERS', null, null],
  'ITM-AD-361': ['VALVES', 'VALVES_MISC', null, null],
  'ITM-AD-380': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AD-381': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AD-382': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-386': ['PUMPS', 'PUMPS_MOTORS', null, null],
  'ITM-AD-388': ['FINISHING', 'INSULATION', null, null],
  'ITM-AD-390': ['SCAFFOLDING', 'SCAFFOLD_TUBES', null, null],
  'ITM-AD-392': ['PIPES', 'PLASTIC_PIPES', 'DN 300', 300],
  'ITM-AD-393': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AD-394': ['CONSTRUCTION', 'CEMENT_AGGREGATES', null, null],
  'ITM-AD-396': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-398': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AD-399': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-400': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-401': ['PUMPS', 'HOSES', null, null],
  'ITM-AD-404': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AD-406': ['FITTINGS', 'FITTINGS_MISC', null, null],
  'ITM-AD-408': ['FINISHING', 'INSULATION', null, null],
  'ITM-AD-410': ['FINISHING', 'PAINTS', null, null],
  'ITM-AD-411': ['FINISHING', 'TILES', null, null],
  'ITM-AD-419': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AD-422': ['SAFETY', null, null, null],
  'ITM-AD-423': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-424': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-425': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-428': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-429': ['FITTINGS', 'FITTINGS_MISC', '4 انج', 101.6],
  'ITM-AD-430': ['FITTINGS', 'BENDS', '2 انج', 50.8],
  'ITM-AD-431': ['FITTINGS', 'BENDS', '3 انج', 76.2],
  'ITM-AD-432': ['PIPES', 'STEEL_PIPES', '3 انج', 76.2],
  'ITM-AD-433': ['PIPES', 'STEEL_PIPES', '2 انج', 50.8],
  'ITM-AD-434': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-435': ['PIPES', 'STEEL_PIPES', '2 انج', 50.8],
  'ITM-AD-436': ['FITTINGS', 'FITTINGS_MISC', '4 انج', 101.6],
  'ITM-AD-437': ['SANITARY', null, null, null],
  'ITM-AD-438': ['PIPES', 'STEEL_PIPES', '2 انج', 50.8],
  'ITM-AD-439': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-440': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-441': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-442': ['CONSTRUCTION', 'TIMBER', null, null],
  'ITM-AD-443': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-444': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-445': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-446': ['PUMPS', 'HOSES', '2 انج', 50.8],
  'ITM-AD-447': ['PUMPS', 'HOSES', '3 انج', 76.2],
  'ITM-AD-448': ['PIPES', 'STEEL_PIPES', null, null],
  'ITM-AD-449': ['PIPES', 'STEEL_PIPES', null, null],
  'ITM-AD-450': ['PIPES', 'STEEL_PIPES', null, null],
  'ITM-AD-451': ['CONSTRUCTION', 'TIMBER', null, null],
  'ITM-AD-452': ['FINISHING', 'TILES', null, null],
  'ITM-AD-453': ['FINISHING', 'TILES', null, null],
  'ITM-AD-454': ['FINISHING', 'TILES', null, null],
  'ITM-AD-455': ['FINISHING', 'TILES', null, null],
  'ITM-AD-457': ['FINISHING', 'INSULATION', null, null],
  'ITM-AD-461': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AD-463': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-465': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-473': ['FITTINGS', 'BENDS', 'DN 900', 900],
  'ITM-AD-474': ['FITTINGS', 'BENDS', 'DN 900', 900],
  'ITM-AD-475': ['FITTINGS', 'BENDS', 'DN 900', 900],
  'ITM-AD-476': ['FITTINGS', 'FITTINGS_MISC', 'DN 900', 900],
  'ITM-AD-477': ['FITTINGS', 'BENDS', 'DN 900', 900],
  'ITM-AD-479': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-481': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-482': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AD-483': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-484': ['PIPES', 'STEEL_PIPES', '100 انج', 2540],
  'ITM-AD-485': ['PIPES', 'STEEL_PIPES', '30 انج', 762],
  'ITM-AD-486': ['PIPES', 'STEEL_PIPES', '30 انج', 762],
  'ITM-AD-487': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AD-488': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AD-489': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AD-490': ['PIPES', 'DUCTILE', 'DN 700', 700],
  'ITM-AD-491': ['PIPES', 'DUCTILE', 'DN 800', 800],
  'ITM-AD-492': ['PIPES', 'DUCTILE', 'DN 150', 150],
  'ITM-AD-493': ['PIPES', 'DUCTILE', 'DN 100', 100],
  'ITM-AD-494': ['PIPES', 'DUCTILE', 'DN 100', 100],
  'ITM-AD-495': ['PIPES', 'DUCTILE', 'DN 500', 500],
  'ITM-AD-496': ['PIPES', 'DUCTILE', 'DN 250', 250],
  'ITM-AD-497': ['PIPES', 'DUCTILE', 'DN 300', 300],
  'ITM-AD-498': ['PIPES', 'DUCTILE', 'DN 600', 600],
  'ITM-AD-499': ['PIPES', 'STEEL_PIPES', 'DN 800', 800],
  'ITM-AD-500': ['PIPES', 'PLASTIC_PIPES', 'DN 400', 400],
  'ITM-AD-501': ['PIPES', 'PLASTIC_PIPES', 'DN 550', 550],
  'ITM-AD-502': ['PIPES', 'STEEL_PIPES', 'DN 600', 600],
  'ITM-AD-503': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-504': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-505': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-506': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-507': ['SCAFFOLDING', 'SCAFFOLD_TUBES', null, null],
  'ITM-AD-508': ['SCAFFOLDING', 'SCAFFOLD_TUBES', null, null],
  'ITM-AD-509': ['SCAFFOLDING', 'SCAFFOLD_TUBES', null, null],
  'ITM-AD-510': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-511': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-512': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-513': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-514': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-515': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-516': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-517': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-518': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AD-519': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AD-520': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-521': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AD-522': ['CONSTRUCTION', 'CEMENT_AGGREGATES', null, null],
  'ITM-AD-523': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-524': ['PIPES', 'STEEL_PIPES', '70 انج', 1778],
  'ITM-AD-525': ['PIPES', 'STEEL_PIPES', '90 انج', 2286],
  'ITM-AD-526': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-527': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-528': ['PIPES', 'STEEL_PIPES', '30 انج', 762],
  'ITM-AD-529': ['SITE', 'CABINS', null, null],
  'ITM-AD-530': ['SITE', 'CABINS', null, null],
  'ITM-AD-531': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AD-532': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AD-533': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-534': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AD-535': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AD-536': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AD-537': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AD-538': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AD-539': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AD-540': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AD-541': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AD-542': ['PIPES', 'STEEL_PIPES', '1/2 انج', 12.7],
  'ITM-AD-543': ['FITTINGS', 'COUPLINGS', null, null],
  'ITM-AD-544': ['FITTINGS', 'BENDS', 'DN 400', 400],
  'ITM-AD-545': ['FITTINGS', 'FITTINGS_MISC', null, null],
  'ITM-AD-546': ['FITTINGS', 'COUPLINGS', 'DN 500', 500],
  'ITM-AD-547': ['FITTINGS', 'BENDS', 'DN 300', 300],
  'ITM-AD-548': ['FITTINGS', 'REDUCERS', 'DN 600', 600],
  'ITM-AD-549': ['FITTINGS', 'REDUCERS', 'DN 400', 400],
  'ITM-AD-550': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-551': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-553': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-554': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-555': ['PUMPS', 'HOSES', '2 انج', 50.8],
  'ITM-AD-556': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-557': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-558': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-559': ['PUMPS', 'HOSES', '2 انج', 50.8],
  'ITM-AD-560': ['SCAFFOLDING', 'SCAFFOLD_TUBES', null, null],
  'ITM-AD-561': ['PUMPS', 'HOSES', '4 انج', 101.6],
  'ITM-AD-562': ['PUMPS', 'HOSES', '2 انج', 50.8],
  'ITM-AD-563': ['PUMPS', 'HOSES', '4 انج', 101.6],
  'ITM-AD-564': ['PUMPS', 'HOSES', '3 انج', 76.2],
  'ITM-AD-565': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AD-566': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-567': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-568': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-569': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-570': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-571': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-572': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-573': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-574': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-575': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-576': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-577': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-578': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-579': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-580': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-581': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-582': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-583': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-584': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-585': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-586': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-587': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-588': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-589': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-590': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-591': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-592': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-593': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-594': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-595': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-596': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-597': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-598': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-599': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-600': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-601': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-602': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AD-603': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-604': ['PUMPS', 'HOSES', '2 انج', 50.8],
  'ITM-AD-605': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-606': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-607': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AD-609': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AD-610': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AD-611': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-612': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AD-613': ['SCAFFOLDING', 'SCAFFOLD_CLAMPS', null, null],
  'ITM-AD-614': ['SCAFFOLDING', 'SCAFFOLD_CLAMPS', null, null],
  'ITM-AD-615': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AD-616': ['CONSTRUCTION', 'TIMBER', null, null],
  'ITM-AD-618': ['FITTINGS', 'BENDS', 'DN 125', 125],
  'ITM-AD-619': ['FITTINGS', 'BENDS', 'DN 200', 200],
  'ITM-AD-620': ['FITTINGS', 'BENDS', 'DN 200', 200],
  'ITM-AD-621': ['FITTINGS', 'BENDS', 'DN 200', 200],
  'ITM-AD-622': ['FITTINGS', 'BENDS', 'DN 250', 250],
  'ITM-AD-623': ['FITTINGS', 'BENDS', 'DN 250', 250],
  'ITM-AD-624': ['FITTINGS', 'BENDS', 'DN 300', 300],
  'ITM-AD-625': ['FITTINGS', 'BENDS', 'DN 300', 300],
  'ITM-AD-626': ['FITTINGS', 'BENDS', 'DN 400', 400],
  'ITM-AD-627': ['FITTINGS', 'BENDS', 'DN 400', 400],
  'ITM-AD-628': ['FITTINGS', 'BENDS', 'DN 500', 500],
  'ITM-AD-629': ['FITTINGS', 'BENDS', 'DN 500', 500],
  'ITM-AD-630': ['FITTINGS', 'BENDS', 'DN 500', 500],
  'ITM-AD-631': ['FITTINGS', 'BENDS', 'DN 500', 500],
  'ITM-AD-632': ['FITTINGS', 'BENDS', 'DN 500', 500],
  'ITM-AD-633': ['FITTINGS', 'BENDS', 'DN 600', 600],
  'ITM-AD-634': ['FITTINGS', 'BENDS', 'DN 600', 600],
  'ITM-AD-635': ['FITTINGS', 'BENDS', 'DN 600', 600],
  'ITM-AD-636': ['FITTINGS', 'BENDS', 'DN 600', 600],
  'ITM-AD-637': ['FITTINGS', 'BENDS', 'DN 600', 600],
  'ITM-AD-638': ['FITTINGS', 'BENDS', 'DN 700', 700],
  'ITM-AD-639': ['FITTINGS', 'BENDS', 'DN 700', 700],
  'ITM-AD-640': ['FITTINGS', 'BENDS', 'DN 700', 700],
  'ITM-AD-641': ['FITTINGS', 'BENDS', 'DN 700', 700],
  'ITM-AD-642': ['FITTINGS', 'BENDS', 'DN 700', 700],
  'ITM-AD-643': ['FITTINGS', 'BENDS', 'DN 700', 700],
  'ITM-AD-644': ['FITTINGS', 'BENDS', 'DN 800', 800],
  'ITM-AD-645': ['FITTINGS', 'BENDS', 'DN 900', 900],
  'ITM-AD-646': ['FITTINGS', 'BENDS', 'DN 900', 900],
  'ITM-AD-647': ['FITTINGS', 'BENDS', 'DN 900', 900],
  'ITM-AD-648': ['FITTINGS', 'BENDS', 'DN 900', 900],
  'ITM-AD-649': ['FITTINGS', 'BENDS', 'DN 900', 900],
  'ITM-AD-650': ['FITTINGS', 'BENDS', 'DN 1000', 1000],
  'ITM-AD-651': ['FITTINGS', 'BENDS', 'DN 1000', 1000],
  'ITM-AD-652': ['FITTINGS', 'BENDS', 'DN 1000', 1000],
  'ITM-AD-654': ['FITTINGS', 'FITTINGS_MISC', 'DN 250', 250],
  'ITM-AD-655': ['FITTINGS', 'FITTINGS_MISC', 'DN 200', 200],
  'ITM-AD-656': ['FITTINGS', 'FITTINGS_MISC', 'DN 150', 150],
  'ITM-AD-657': ['FITTINGS', 'FITTINGS_MISC', 'DN 400', 400],
  'ITM-AD-658': ['FITTINGS', 'FITTINGS_MISC', 'DN 400', 400],
  'ITM-AD-659': ['FITTINGS', 'FITTINGS_MISC', 'DN 400', 400],
  'ITM-AD-660': ['FITTINGS', 'FITTINGS_MISC', 'DN 400', 400],
  'ITM-AD-661': ['FITTINGS', 'FITTINGS_MISC', 'DN 400', 400],
  'ITM-AD-662': ['FITTINGS', 'FITTINGS_MISC', 'DN 450', 450],
  'ITM-AD-663': ['FITTINGS', 'FITTINGS_MISC', 'DN 400', 400],
  'ITM-AD-664': ['FITTINGS', 'FITTINGS_MISC', 'DN 300', 300],
  'ITM-AD-665': ['FITTINGS', 'FITTINGS_MISC', 'DN 500', 500],
  'ITM-AD-666': ['FITTINGS', 'FITTINGS_MISC', 'DN 500', 500],
  'ITM-AD-667': ['FITTINGS', 'FITTINGS_MISC', 'DN 500', 500],
  'ITM-AD-668': ['FITTINGS', 'FITTINGS_MISC', 'DN 500', 500],
  'ITM-AD-669': ['FITTINGS', 'FITTINGS_MISC', 'DN 600', 600],
  'ITM-AD-670': ['FITTINGS', 'FITTINGS_MISC', 'DN 600', 600],
  'ITM-AD-671': ['FITTINGS', 'FITTINGS_MISC', 'DN 600', 600],
  'ITM-AD-672': ['FITTINGS', 'FITTINGS_MISC', 'DN 600', 600],
  'ITM-AD-673': ['FITTINGS', 'FITTINGS_MISC', 'DN 600', 600],
  'ITM-AD-674': ['FITTINGS', 'FITTINGS_MISC', 'DN 600', 600],
  'ITM-AD-675': ['FITTINGS', 'FITTINGS_MISC', 'DN 600', 600],
  'ITM-AD-676': ['FITTINGS', 'FITTINGS_MISC', 'DN 600', 600],
  'ITM-AD-677': ['FITTINGS', 'FITTINGS_MISC', 'DN 600', 600],
  'ITM-AD-678': ['FITTINGS', 'FITTINGS_MISC', 'DN 700', 700],
  'ITM-AD-679': ['FITTINGS', 'FITTINGS_MISC', 'DN 900', 900],
  'ITM-AD-680': ['FITTINGS', 'FITTINGS_MISC', 'DN 900', 900],
  'ITM-AD-681': ['FITTINGS', 'FITTINGS_MISC', 'DN 900', 900],
  'ITM-AD-682': ['FITTINGS', 'FITTINGS_MISC', 'DN 100', 100],
  'ITM-AD-684': ['FITTINGS', 'COUPLINGS', 'DN 500', 500],
  'ITM-AD-685': ['FITTINGS', 'COUPLINGS', 'DN 600', 600],
  'ITM-AD-686': ['FITTINGS', 'COUPLINGS', 'DN 700', 700],
  'ITM-AD-687': ['FITTINGS', 'COUPLINGS', 'DN 700', 700],
  'ITM-AD-688': ['FITTINGS', 'COUPLINGS', 'DN 800', 800],
  'ITM-AD-689': ['FITTINGS', 'COUPLINGS', 'DN 400', 400],
  'ITM-AD-690': ['FITTINGS', 'COUPLINGS', 'DN 500', 500],
  'ITM-AD-691': ['FITTINGS', 'COUPLINGS', 'DN 600', 600],
  'ITM-AD-692': ['FITTINGS', 'COUPLINGS', 'DN 600', 600],
  'ITM-AD-693': ['FITTINGS', 'COUPLINGS', 'DN 600', 600],
  'ITM-AD-694': ['FITTINGS', 'COUPLINGS', 'DN 600', 600],
  'ITM-AD-695': ['FITTINGS', 'COUPLINGS', 'DN 650', 650],
  'ITM-AD-696': ['FITTINGS', 'COUPLINGS', 'DN 700', 700],
  'ITM-AD-697': ['FITTINGS', 'COUPLINGS', 'DN 900', 900],
  'ITM-AD-698': ['FITTINGS', 'COUPLINGS', 'DN 900', 900],
  'ITM-AD-699': ['FITTINGS', 'COUPLINGS', 'DN 400', 400],
  'ITM-AD-700': ['FITTINGS', 'COUPLINGS', 'DN 100', 100],
  'ITM-AD-701': ['FITTINGS', 'COUPLINGS', 'DN 150', 150],
  'ITM-AD-702': ['FITTINGS', 'COUPLINGS', 'DN 300', 300],
  'ITM-AD-703': ['FITTINGS', 'COUPLINGS', 'DN 350', 350],
  'ITM-AD-705': ['FITTINGS', 'COUPLINGS', 'DN 400', 400],
  'ITM-AD-706': ['FITTINGS', 'COUPLINGS', 'DN 500', 500],
  'ITM-AD-707': ['FITTINGS', 'COUPLINGS', 'DN 600', 600],
  'ITM-AD-708': ['FITTINGS', 'COUPLINGS', 'DN 700', 700],
  'ITM-AD-709': ['FITTINGS', 'REDUCERS', 'DN 600', 600],
  'ITM-AD-710': ['FITTINGS', 'REDUCERS', 'DN 600', 600],
  'ITM-AD-711': ['FITTINGS', 'REDUCERS', 'DN 600', 600],
  'ITM-AD-712': ['FITTINGS', 'REDUCERS', 'DN 150', 150],
  'ITM-AD-713': ['FITTINGS', 'REDUCERS', 'DN 80', 80],
  'ITM-AD-714': ['FITTINGS', 'REDUCERS', 'DN 100', 100],
  'ITM-AD-715': ['FITTINGS', 'REDUCERS', 'DN 250', 250],
  'ITM-AD-716': ['FITTINGS', 'REDUCERS', 'DN 150', 150],
  'ITM-AD-717': ['FITTINGS', 'REDUCERS', 'DN 350', 350],
  'ITM-AD-718': ['FITTINGS', 'REDUCERS', 'DN 600', 600],
  'ITM-AD-719': ['FITTINGS', 'REDUCERS', 'DN 700', 700],
  'ITM-AD-720': ['FITTINGS', 'REDUCERS', 'DN 600', 600],
  'ITM-AD-721': ['FITTINGS', 'REDUCERS', 'DN 400', 400],
  'ITM-AD-722': ['FITTINGS', 'REDUCERS', 'DN 600', 600],
  'ITM-AD-723': ['FITTINGS', 'REDUCERS', 'DN 350', 350],
  'ITM-AD-724': ['FITTINGS', 'REDUCERS', 'DN 80', 80],
  'ITM-AD-725': ['FITTINGS', 'REDUCERS', 'DN 300', 300],
  'ITM-AD-726': ['FITTINGS', 'REDUCERS', 'DN 300', 300],
  'ITM-AD-727': ['FITTINGS', 'COUPLINGS', 'DN 800', 800],
  'ITM-AD-728': ['FITTINGS', 'COUPLINGS', 'DN 100', 100],
  'ITM-AD-729': ['FITTINGS', 'FLANGES', 'DN 100', 100],
  'ITM-AD-731': ['FITTINGS', 'GLANDS', 'DN 100', 100],
  'ITM-AD-732': ['FITTINGS', 'GLANDS', 'DN 200', 200],
  'ITM-AD-733': ['FITTINGS', 'GLANDS', 'DN 300', 300],
  'ITM-AD-734': ['FITTINGS', 'GLANDS', 'DN 400', 400],
  'ITM-AD-735': ['FITTINGS', 'GLANDS', 'DN 500', 500],
  'ITM-AD-736': ['FITTINGS', 'GLANDS', 'DN 600', 600],
  'ITM-AD-737': ['FITTINGS', 'GLANDS', 'DN 700', 700],
  'ITM-AD-738': ['FITTINGS', 'GLANDS', 'DN 800', 800],
  'ITM-AD-739': ['FITTINGS', 'GASKETS', 'DN 400', 400],
  'ITM-AD-740': ['FITTINGS', 'GASKETS', 'DN 700', 700],
  'ITM-AD-741': ['FITTINGS', 'GASKETS', 'DN 800', 800],
  'ITM-AD-743': ['FITTINGS', 'FLANGES', 'DN 900', 900],
  'ITM-AD-744': ['FITTINGS', 'FLANGES', 'DN 200', 200],
  'ITM-AD-746': ['FITTINGS', 'FLANGES', 'DN 700', 700],
  'ITM-AD-747': ['FITTINGS', 'FLANGES', 'DN 300', 300],
  'ITM-AD-748': ['FITTINGS', 'FLANGES', 'DN 200', 200],
  'ITM-AD-750': ['PIPES', 'STEEL_PIPES', 'DN 300', 300],
  'ITM-AD-751': ['PIPES', 'DUCTILE', 'DN 600', 600],
  'ITM-AD-752': ['PIPES', 'DUCTILE', 'DN 600', 600],
  'ITM-AD-753': ['PIPES', 'DUCTILE', 'DN 400', 400],
  'ITM-AD-754': ['PIPES', 'STEEL_PIPES', 'DN 400', 400],
  'ITM-AD-755': ['PIPES', 'DUCTILE', 'DN 300', 300],
  'ITM-AD-756': ['PIPES', 'DUCTILE', 'DN 700', 700],
  'ITM-AD-X01': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AD-X02': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-X03': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-X04': ['PUMPS', 'SUBMERSIBLES', null, null],
  'ITM-AD-X05': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AD-X06': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AD-X07': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-X08': ['EQUIPMENT', 'GENERATORS', null, null],
  'ITM-AD-X09': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-X10': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AD-X11': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AD-X12': ['SANITARY', null, null, null],
  'ITM-AD-X13': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AD-X14': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-X15': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-X16': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-X17': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-X18': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AD-X19': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AD-X20': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AD-X21': ['SANITARY', null, null, null],
  'ITM-AD-X22': ['SITE', 'SITE_MISC', null, null],
  'ITM-AD-X23': ['PUMPS', 'HOSES', null, null],
  'ITM-AD-X24': ['PUMPS', 'HOSES', '2 انج', 50.8],
  'ITM-AD-X25': ['PUMPS', 'HOSES', '3 انج', 76.2],
  'ITM-AD-X26': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-X27': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AD-X28': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AG-002': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AG-003': ['PIPES', 'PLASTIC_PIPES', null, null],
  'ITM-AG-004': ['SCAFFOLDING', 'SCAFFOLD_CLAMPS', null, null],
  'ITM-AG-005': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AG-007': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-008': ['SAFETY', null, null, null],
  'ITM-AG-009': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-010': ['PUMPS', 'PUMPS_MOTORS', null, null],
  'ITM-AG-011': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-012': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AG-013': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AG-014': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-015': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AG-016': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-017': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-018': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-019': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AG-020': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AG-021': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AG-022': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AG-023': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AG-024': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AG-025': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AG-026': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AG-027': ['FINISHING', 'PAINTS', null, null],
  'ITM-AG-028': ['FINISHING', 'PAINTS', null, null],
  'ITM-AG-029': ['FINISHING', 'PAINTS', null, null],
  'ITM-AG-030': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AG-031': ['SAFETY', null, null, null],
  'ITM-AG-032': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-033': ['SAFETY', null, null, null],
  'ITM-AG-034': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AG-035': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AG-036': ['SAFETY', null, null, null],
  'ITM-AG-038': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-039': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AG-040': ['SAFETY', null, null, null],
  'ITM-AG-041': ['SAFETY', null, null, null],
  'ITM-AG-042': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-043': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-044': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AG-045': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AG-047': ['SCAFFOLDING', 'SCAFFOLD_CLAMPS', null, null],
  'ITM-AG-048': ['SAFETY', null, null, null],
  'ITM-AG-049': ['SAFETY', null, null, null],
  'ITM-AG-054': ['PIPES', 'PLASTIC_PIPES', null, null],
  'ITM-AG-056': ['FINISHING', 'FINISHING_MISC', null, null],
  'ITM-AG-057': ['FINISHING', 'TILES', null, null],
  'ITM-AG-058': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AG-059': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AG-060': ['CONSTRUCTION', 'TIMBER', null, null],
  'ITM-AG-061': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AG-062': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AG-063': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AG-064': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AG-065': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AG-066': ['EQUIPMENT', 'GENERATORS', null, null],
  'ITM-AG-067': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-068': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AG-069': ['EQUIPMENT', 'GENERATORS', null, null],
  'ITM-AG-070': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AG-071': ['EQUIPMENT', 'GENERATORS', null, null],
  'ITM-AG-072': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-073': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AG-074': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AG-075': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AG-076': ['PUMPS', 'PUMPS_MOTORS', null, null],
  'ITM-AG-077': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-078': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AG-079': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-080': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AG-081': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-082': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AG-083': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-084': ['PUMPS', 'HOSES', null, null],
  'ITM-AG-085': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-086': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AG-087': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AG-088': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-089': ['PUMPS', 'PUMPS_MOTORS', null, null],
  'ITM-AG-090': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AG-091': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AG-092': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AG-093': ['FITTINGS', 'COUPLINGS', 'DN 900', 900],
  'ITM-AG-094': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-095': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AG-096': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-097': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-098': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-099': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-100': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-101': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-102': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AG-104': ['PUMPS', 'PUMPS_MOTORS', null, null],
  'ITM-AG-105': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AG-106': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AG-107': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AG-108': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AG-109': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-110': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AG-111': ['SITE', 'SITE_MISC', null, null],
  'ITM-AG-112': ['TOOLS', 'HAND_TOOLS', null, null],
  'ITM-AG-113': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-115': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-116': ['EQUIPMENT', 'DRILLING_EQ', null, null],
  'ITM-AG-117': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-119': ['VALVES', 'GATE_VALVES', 'DN 1000', 1000],
  'ITM-AG-120': ['VALVES', 'GATE_VALVES', 'DN 900', 900],
  'ITM-AG-121': ['VALVES', 'GATE_VALVES', 'DN 600', 600],
  'ITM-AG-122': ['VALVES', 'GATE_VALVES', 'DN 600', 600],
  'ITM-AG-123': ['VALVES', 'GATE_VALVES', 'DN 600', 600],
  'ITM-AG-124': ['VALVES', 'GATE_VALVES', 'DN 600', 600],
  'ITM-AG-125': ['VALVES', 'GATE_VALVES', 'DN 600', 600],
  'ITM-AG-126': ['VALVES', 'GATE_VALVES', 'DN 500', 500],
  'ITM-AG-127': ['VALVES', 'GATE_VALVES', 'DN 400', 400],
  'ITM-AG-128': ['VALVES', 'GATE_VALVES', 'DN 350', 350],
  'ITM-AG-130': ['VALVES', 'VALVES_MISC', 'DN 700', 700],
  'ITM-AG-131': ['VALVES', 'VALVES_MISC', 'DN 600', 600],
  'ITM-AG-132': ['VALVES', 'VALVES_MISC', 'DN 500', 500],
  'ITM-AG-133': ['VALVES', 'VALVES_MISC', 'DN 400', 400],
  'ITM-AG-134': ['VALVES', 'VALVES_MISC', 'DN 300', 300],
  'ITM-AG-135': ['VALVES', 'VALVES_MISC', 'DN 200', 200],
  'ITM-AG-136': ['VALVES', 'VALVES_MISC', 'DN 250', 250],
  'ITM-AG-138': ['VALVES', 'BUTTERFLY_VALVES', 'DN 600', 600],
  'ITM-AG-139': ['VALVES', 'BUTTERFLY_VALVES', 'DN 500', 500],
  'ITM-AG-140': ['VALVES', 'BUTTERFLY_VALVES', 'DN 400', 400],
  'ITM-AG-141': ['VALVES', 'BUTTERFLY_VALVES', 'DN 300', 300],
  'ITM-AG-143': ['VALVES', 'VALVES_MISC', 'DN 600', 600],
  'ITM-AG-144': ['VALVES', 'VALVES_MISC', 'DN 500', 500],
  'ITM-AG-145': ['VALVES', 'VALVES_MISC', 'DN 400', 400],
  'ITM-AG-146': ['VALVES', 'VALVES_MISC', 'DN 300', 300],
  'ITM-AG-148': ['SCAFFOLDING', 'SCAFFOLD_TUBES', null, null],
  'ITM-AG-149': ['SCAFFOLDING', 'SCAFFOLD_TUBES', null, null],
  'ITM-AG-150': ['CONSTRUCTION', 'CEMENT_AGGREGATES', null, null],
  'ITM-AG-151': ['OTHER', null, null, null],
  'ITM-AG-154': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AG-155': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AG-157': ['FITTINGS', 'COUPLINGS', 'DN 600', 600],
  'ITM-AG-158': ['FITTINGS', 'COUPLINGS', 'DN 700', 700],
  'ITM-AG-159': ['SITE', 'CABINS', null, null],
  'ITM-AG-160': ['FITTINGS', 'GLANDS', null, null],
  'ITM-AG-161': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AG-162': ['SITE', 'CABINS', null, null],
  'ITM-AG-163': ['FITTINGS', 'FLANGES', 'DN 700', 700],
  'ITM-AG-165': ['FITTINGS', 'FLANGES', 'DN 500', 500],
  'ITM-AG-166': ['FITTINGS', 'FLANGES', 'DN 500', 500],
  'ITM-AG-167': ['FITTINGS', 'FLANGES', 'DN 500', 500],
  'ITM-AG-168': ['SITE', 'CABINS', null, null],
  'ITM-AG-169': ['FITTINGS', 'COUPLINGS', 'DN 700', 700],
  'ITM-AG-170': ['FITTINGS', 'COUPLINGS', 'DN 600', 600],
  'ITM-AG-171': ['FITTINGS', 'COUPLINGS', 'DN 500', 500],
  'ITM-AG-172': ['FITTINGS', 'COUPLINGS', 'DN 400', 400],
  'ITM-AG-173': ['FITTINGS', 'COUPLINGS', 'DN 300', 300],
  'ITM-AG-174': ['FITTINGS', 'COUPLINGS', 'DN 500', 500],
  'ITM-AG-175': ['FITTINGS', 'COUPLINGS', 'DN 250', 250],
  'ITM-AG-176': ['FITTINGS', 'COUPLINGS', 'DN 400', 400],
  'ITM-AG-177': ['FITTINGS', 'COUPLINGS', 'DN 150', 150],
  'ITM-AG-178': ['FITTINGS', 'COUPLINGS', null, null],
  'ITM-AG-179': ['FITTINGS', 'COUPLINGS', 'DN 600', 600],
  'ITM-AG-180': ['FITTINGS', 'COUPLINGS', 'DN 500', 500],
  'ITM-AG-181': ['FITTINGS', 'COUPLINGS', 'DN 500', 500],
  'ITM-AG-182': ['FITTINGS', 'COUPLINGS', 'DN 400', 400],
  'ITM-AG-183': ['FITTINGS', 'COUPLINGS', 'DN 300', 300],
  'ITM-AG-184': ['FITTINGS', 'COUPLINGS', 'DN 350', 350],
  'ITM-AG-185': ['FITTINGS', 'COUPLINGS', 'DN 350', 350],
  'ITM-AG-186': ['FITTINGS', 'COUPLINGS', 'DN 250', 250],
  'ITM-AG-187': ['FITTINGS', 'COUPLINGS', 'DN 200', 200],
  'ITM-AG-188': ['FITTINGS', 'COUPLINGS', 'DN 150', 150],
  'ITM-AG-189': ['FITTINGS', 'COUPLINGS', 'DN 125', 125],
  'ITM-AG-190': ['FITTINGS', 'COUPLINGS', 'DN 80', 80],
  'ITM-AG-191': ['FITTINGS', 'COUPLINGS', 'DN 50', 50],
  'ITM-AG-192': ['FITTINGS', 'COUPLINGS', null, null],
  'ITM-AG-193': ['FITTINGS', 'FLANGES', 'DN 800', 800],
  'ITM-AG-194': ['FITTINGS', 'FLANGES', 'DN 600', 600],
  'ITM-AG-195': ['FITTINGS', 'FLANGES', 'DN 500', 500],
  'ITM-AG-196': ['FITTINGS', 'FLANGES', 'DN 400', 400],
  'ITM-AG-197': ['FITTINGS', 'FLANGES', 'DN 350', 350],
  'ITM-AG-198': ['FITTINGS', 'FLANGES', 'DN 200', 200],
  'ITM-AG-199': ['FITTINGS', 'FLANGES', 'DN 100', 100],
  'ITM-AG-200': ['FITTINGS', 'FLANGES', 'DN 150', 150],
  'ITM-AG-201': ['FITTINGS', 'FLANGES', 'DN 80', 80],
  'ITM-AG-202': ['FITTINGS', 'FLANGES', 'DN 800', 800],
  'ITM-AG-203': ['FITTINGS', 'COUPLINGS', 'DN 500', 500],
  'ITM-AG-204': ['FITTINGS', 'COUPLINGS', 'DN 300', 300],
  'ITM-AG-205': ['SITE', 'CABINS', null, null],
  'ITM-AG-206': ['SITE', 'CABINS', null, null],
  'ITM-AG-207': ['SITE', 'CABINS', null, null],
  'ITM-AG-208': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AG-209': ['FITTINGS', 'FITTINGS_MISC', null, null],
  'ITM-AG-210': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AG-211': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AG-212': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AG-213': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AG-214': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AG-215': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AG-216': ['ELECTRICAL', 'CABLES', null, null],
  'ITM-AG-217': ['SITE', 'CABINS', null, null],
  'ITM-AG-218': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AG-219': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AG-220': ['ELECTRICAL', 'ELECTRICAL_MISC', null, null],
  'ITM-AG-221': ['SITE', 'CABINS', null, null],
  'ITM-AG-222': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AG-223': ['CONSTRUCTION', 'STEEL_SECTIONS', null, null],
  'ITM-AG-224': ['SITE', 'CABINS', null, null],
  'ITM-AG-225': ['SITE', 'CABINS', null, null],
  'ITM-AG-226': ['CONSTRUCTION', 'TIMBER', null, null],
  'ITM-AG-227': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AG-228': ['SITE', 'CABINS', null, null],
  'ITM-AG-229': ['FITTINGS', 'GLANDS', 'DN 900', 900],
  'ITM-AG-230': ['FITTINGS', 'GLANDS', 'DN 800', 800],
  'ITM-AG-231': ['FITTINGS', 'GLANDS', 'DN 700', 700],
  'ITM-AG-232': ['FITTINGS', 'GLANDS', 'DN 600', 600],
  'ITM-AG-233': ['FITTINGS', 'GLANDS', 'DN 300', 300],
  'ITM-AG-234': ['FITTINGS', 'GLANDS', 'DN 200', 200],
  'ITM-AG-235': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AG-236': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AG-237': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AG-238': ['VALVES', 'VALVES_MISC', 'DN 300', 300],
  'ITM-AG-240': ['FITTINGS', 'FLANGES', 'DN 700', 700],
  'ITM-AG-241': ['SITE', 'CABINS', null, null],
  'ITM-AG-242': ['PIPES', 'STEEL_PIPES', null, null],
  'ITM-AG-243': ['CONSTRUCTION', 'CEMENT_AGGREGATES', null, null],
  'ITM-AG-244': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AG-245': ['CONSTRUCTION', 'CEMENT_AGGREGATES', null, null],
  'ITM-AG-246': ['TOOLS', null, null, null],
  'ITM-AG-247': ['TOOLS', null, null, null],
  'ITM-AG-248': ['TOOLS', null, null, null],
  'ITM-AG-249': ['TOOLS', null, null, null],
  'ITM-AG-250': ['SITE', 'CABINS', null, null],
  'ITM-AG-251': ['CONSTRUCTION', 'CONSTRUCTION_MISC', null, null],
  'ITM-AG-252': ['FINISHING', 'INSULATION', null, null],
  'ITM-AG-253': ['PIPES', 'STEEL_PIPES', null, null],
  'ITM-AG-254': ['SITE', 'CABINS', null, null],
  'ITM-AG-255': ['SITE', 'SITE_MISC', null, null],
  'ITM-AG-256': ['SITE', 'SITE_MISC', null, null],
  'ITM-AG-258': ['SITE', 'CABINS', null, null],
  'ITM-AG-259': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AG-260': ['SCAFFOLDING', 'SCAFFOLD_TUBES', null, null],
  'ITM-AG-261': ['SITE', 'CABINS', null, null],
  'ITM-AG-262': ['SCAFFOLDING', 'SCAFFOLD_MISC', null, null],
  'ITM-AG-263': ['SCAFFOLDING', 'SCAFFOLD_TUBES', null, null],
  'ITM-AG-264': ['SITE', 'CABINS', null, null],
  'ITM-AG-265': ['OTHER', null, null, null],
  'ITM-AG-266': ['FITTINGS', 'BENDS', 'DN 800', 800],
  'ITM-AG-267': ['FITTINGS', 'COUPLINGS', 'DN 700', 700],
  'ITM-AG-268': ['FITTINGS', 'COUPLINGS', 'DN 700', 700],
  'ITM-AG-269': ['VALVES', 'VALVES_MISC', 'DN 700', 700],
  'ITM-AG-270': ['VALVES', 'VALVES_MISC', 'DN 600', 600],
  'ITM-AG-271': ['VALVES', 'VALVES_MISC', 'DN 1000', 1000],
  'ITM-AG-272': ['VALVES', 'VALVES_MISC', 'DN 700', 700],
  'ITM-AG-273': ['FITTINGS', 'BENDS', 'DN 800', 800],
  'ITM-AG-274': ['FITTINGS', 'GLANDS', 'DN 700', 700],
  'ITM-AG-275': ['FITTINGS', 'GLANDS', 'DN 500', 500],
  'ITM-AG-276': ['FITTINGS', 'COUPLINGS', 'DN 600', 600],
  'ITM-AG-277': ['FITTINGS', 'COUPLINGS', 'DN 500', 500],
  'ITM-AG-278': ['FITTINGS', 'COUPLINGS', 'DN 400', 400],
  'ITM-AG-279': ['FITTINGS', 'COUPLINGS', 'DN 300', 300],
  'ITM-AG-280': ['FITTINGS', 'BENDS', null, null],
  'ITM-AG-281': ['FITTINGS', 'FITTINGS_MISC', null, null],
  'ITM-AG-282': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AG-284': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AG-285': ['ELECTRICAL', 'WIRING_FIXTURES', null, null],
  'ITM-AG-287': ['SITE', 'SITE_MISC', null, null],
  'ITM-AG-288': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-290': ['EQUIPMENT', 'EQUIPMENT_SPARES', null, null],
  'ITM-AG-292': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-293': ['PUMPS', 'SUBMERSIBLES', null, null],
  'ITM-AG-294': ['PUMPS', 'PUMPS_MOTORS', null, null],
  'ITM-AG-295': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-296': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-297': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-298': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-299': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-300': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-301': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-302': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-303': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-304': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-305': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-306': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-307': ['TOOLS', 'POWER_TOOLS', null, null],
  'ITM-AG-309': ['TOOLS', 'FASTENERS', null, null],
  'ITM-AG-311': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AG-312': ['EQUIPMENT', 'APPLIANCES', null, null],
  'ITM-AG-314': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AG-320': ['PIPES', 'PLASTIC_PIPES', '4 انج', 101.6],
  'ITM-AG-326': ['PIPES', 'DUCTILE', 'DN 1000', 1000],
  'ITM-AG-327': ['PIPES', 'DUCTILE', 'DN 1000', 1000],
  'ITM-AG-328': ['PIPES', 'DUCTILE', 'DN 900', 900],
  'ITM-AG-329': ['PIPES', 'DUCTILE', 'DN 800', 800],
  'ITM-AG-330': ['PIPES', 'DUCTILE', 'DN 700', 700],
  'ITM-AG-331': ['PIPES', 'DUCTILE', 'DN 500', 500],
  'ITM-AG-332': ['PIPES', 'DUCTILE', 'DN 500', 500],
  'ITM-AG-333': ['PIPES', 'DUCTILE', 'DN 400', 400],
  'ITM-AG-334': ['PIPES', 'DUCTILE', 'DN 400', 400],
  'ITM-AG-335': ['PIPES', 'DUCTILE', 'DN 400', 400],
  'ITM-AG-336': ['PIPES', 'DUCTILE', 'DN 300', 300],
  'ITM-AG-337': ['PIPES', 'DUCTILE', 'DN 300', 300],
  'ITM-AG-338': ['PIPES', 'DUCTILE', 'DN 250', 250],
  'ITM-AG-339': ['PIPES', 'DUCTILE', 'DN 200', 200],
  'ITM-AG-340': ['PIPES', 'DUCTILE', 'DN 100', 100],
  'ITM-AG-342': ['PIPES', 'PIPE_CUTS', 'DN 600', 600],
  'ITM-AG-343': ['PIPES', 'PIPE_CUTS', 'DN 500', 500],
  'ITM-AG-344': ['PIPES', 'PIPE_CUTS', 'DN 500', 500],
  'ITM-AG-345': ['PIPES', 'PIPE_CUTS', 'DN 700', 700],
  'ITM-AG-346': ['PIPES', 'PIPE_CUTS', 'DN 800', 800],
  'ITM-AG-347': ['PIPES', 'PIPE_CUTS', 'DN 900', 900],
  'ITM-AG-348': ['PIPES', 'PIPE_CUTS', 'DN 400', 400],
  'ITM-AG-349': ['PIPES', 'PIPE_CUTS', 'DN 300', 300],
  'ITM-AG-350': ['PIPES', 'PIPE_CUTS', 'DN 300', 300],
  'ITM-AG-352': ['PIPES', 'STEEL_PIPES', 'DN 1000', 1000],
  'ITM-AG-353': ['PIPES', 'STEEL_PIPES', 'DN 300', 300],
  'ITM-AG-355': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-356': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AG-357': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AG-358': ['FITTINGS', 'FLANGES', 'DN 900', 900],
  'ITM-AG-359': ['FITTINGS', 'FLANGES', 'DN 900', 900],
  'ITM-AG-360': ['FITTINGS', 'FLANGES', 'DN 900', 900],
  'ITM-AG-361': ['EQUIPMENT', 'CONSTRUCTION_EQ', null, null],
  'ITM-AG-362': ['CONSTRUCTION', 'FORMWORK', null, null],
  'ITM-AG-363': ['SITE', 'TANKS_BARRELS', null, null],
  'ITM-AG-364': ['CONSTRUCTION', 'FORMWORK', null, null],
}
