import { registerStrings } from '../../i18n/strings'

// Module-local strings ('debug.*') for the Debug Window developer panel.
registerStrings({
  'debug.title': { ar: 'نافذة التصحيح', en: 'Debug Window' },
  'debug.subtitle': {
    ar: 'لوحة المطوّر — مراقبة النظام والتشخيص في الوقت الحقيقي',
    en: 'Developer panel — real-time system monitoring & diagnostics',
  },
  'debug.live': { ar: 'مباشر', en: 'LIVE' },
  'debug.refreshIn': { ar: 'تحديث خلال', en: 'Refresh in' },
  'debug.seconds': { ar: 'ث', en: 's' },
  'debug.refreshNow': { ar: 'تحديث الآن', en: 'Refresh now' },
  'debug.envBadge': { ar: 'بيئة العرض', en: 'DEMO ENV' },

  // Tabs
  'debug.tab.status': { ar: 'حالة النظام', en: 'System Status' },
  'debug.tab.logs': { ar: 'سجل الأخطاء', en: 'Error Log' },
  'debug.tab.api': { ar: 'مفتش API', en: 'API Inspector' },
  'debug.tab.queries': { ar: 'استعلامات DB', en: 'DB Queries' },
  'debug.tab.users': { ar: 'المستخدمون النشطون', en: 'Active Users' },
  'debug.tab.actions': { ar: 'إجراءات النظام', en: 'System Actions' },

  // System status panel
  'debug.status.apiTime': { ar: 'زمن استجابة API', en: 'API Response Time' },
  'debug.status.apiHint': { ar: 'قياس مباشر من /api/health', en: 'Live ping to /api/health' },
  'debug.status.db': { ar: 'قاعدة البيانات', en: 'Database' },
  'debug.status.dbConnected': { ar: 'متصل', en: 'Connected' },
  'debug.status.dbHint': { ar: 'SQLite — مجمّع الاتصالات نشط', en: 'SQLite — pool active' },
  'debug.status.memory': { ar: 'استهلاك الذاكرة', en: 'Memory Usage' },
  'debug.status.memHint': { ar: 'من إجمالي 4096 ميغابايت', en: 'of 4096 MB total' },
  'debug.status.sessions': { ar: 'الجلسات النشطة', en: 'Active Sessions' },
  'debug.status.sessHint': { ar: 'متصلون الآن', en: 'currently online' },
  'debug.status.jobs': { ar: 'مهام معلّقة', en: 'Pending Jobs' },
  'debug.status.jobsHint': { ar: 'في طابور المعالجة', en: 'in queue' },
  'debug.status.backup': { ar: 'آخر نسخة احتياطية', en: 'Last Backup' },
  'debug.status.backupHint': { ar: 'نسخ تلقائي يومي', en: 'daily auto-backup' },
  'debug.status.uptime': { ar: 'مدة التشغيل', en: 'Uptime' },
  'debug.status.uptimeHint': { ar: 'بدون انقطاع', en: 'without downtime' },
  'debug.status.chartTitle': { ar: 'زمن الاستجابة (آخر 24 قياس)', en: 'Response Time (last 24 samples)' },
  'debug.status.chartSub': { ar: 'بالميلي ثانية', en: 'milliseconds' },
  'debug.status.healthy': { ar: 'سليم', en: 'Healthy' },
  'debug.status.degraded': { ar: 'متدهور', en: 'Degraded' },

  // Logs panel
  'debug.logs.title': { ar: 'وحدة التحكم — البث المباشر', en: 'Console — live stream' },
  'debug.logs.clear': { ar: 'مسح', en: 'Clear' },
  'debug.logs.pause': { ar: 'إيقاف مؤقت', en: 'Pause' },
  'debug.logs.resume': { ar: 'استئناف', en: 'Resume' },
  'debug.logs.level': { ar: 'المستوى', en: 'Level' },
  'debug.logs.all': { ar: 'الكل', en: 'All' },
  'debug.logs.empty': { ar: 'تم مسح وحدة التحكم', en: 'Console cleared' },
  'debug.logs.lines': { ar: 'سطر', en: 'lines' },
  'debug.logs.cleared': { ar: 'تم مسح السجل', en: 'Log cleared' },

  // API inspector
  'debug.api.title': { ar: 'مكالمات API الأخيرة', en: 'Recent API Calls' },
  'debug.api.method': { ar: 'الطريقة', en: 'Method' },
  'debug.api.endpoint': { ar: 'المسار', en: 'Endpoint' },
  'debug.api.status': { ar: 'الحالة', en: 'Status' },
  'debug.api.time': { ar: 'الزمن', en: 'Time' },
  'debug.api.size': { ar: 'الحجم', en: 'Size' },
  'debug.api.when': { ar: 'منذ', en: 'When' },
  'debug.api.real': { ar: 'حقيقي', en: 'real' },
  'debug.api.slow': { ar: 'بطيء', en: 'slow' },
  'debug.api.replay': { ar: 'إعادة تشغيل القياسات الحقيقية', en: 'Replay real probes' },
  'debug.api.replayed': { ar: 'تمت إعادة قياس نقاط النهاية', en: 'Endpoints re-measured' },

  // DB queries
  'debug.db.title': { ar: 'الاستعلامات البطيئة', en: 'Slow Query Log' },
  'debug.db.query': { ar: 'الاستعلام', en: 'Query' },
  'debug.db.table': { ar: 'الجدول', en: 'Table' },
  'debug.db.rows': { ar: 'الصفوف', en: 'Rows' },
  'debug.db.duration': { ar: 'المدة', en: 'Duration' },
  'debug.db.calls': { ar: 'التكرار', en: 'Calls' },
  'debug.db.slowBadge': { ar: 'بطيء', en: 'Slow' },
  'debug.db.fast': { ar: 'سريع', en: 'Fast' },

  // Active users
  'debug.users.title': { ar: 'المستخدمون المتصلون الآن', en: 'Currently Connected Users' },
  'debug.users.user': { ar: 'المستخدم', en: 'User' },
  'debug.users.page': { ar: 'الصفحة الحالية', en: 'Current Page' },
  'debug.users.duration': { ar: 'مدة الجلسة', en: 'Session Duration' },
  'debug.users.ip': { ar: 'عنوان IP', en: 'IP Address' },
  'debug.users.role': { ar: 'الدور', en: 'Role' },
  'debug.users.terminate': { ar: 'إنهاء الجلسة', en: 'Terminate' },
  'debug.users.terminated': { ar: 'تم إنهاء جلسة', en: 'Session terminated:' },

  // System actions
  'debug.actions.title': { ar: 'إجراءات الصيانة', en: 'Maintenance Actions' },
  'debug.actions.subtitle': {
    ar: 'عمليات على مستوى النظام — استخدمها بحذر',
    en: 'System-wide operations — use with care',
  },
  'debug.actions.clearCache': { ar: 'مسح الذاكرة المؤقتة', en: 'Clear Cache' },
  'debug.actions.clearCacheDesc': { ar: 'إفراغ ذاكرة التخزين المؤقت', en: 'Flush in-memory cache' },
  'debug.actions.clearCacheDone': { ar: 'تم مسح الذاكرة المؤقتة بنجاح', en: 'Cache cleared successfully' },
  'debug.actions.reindex': { ar: 'إعادة بناء الفهارس', en: 'Rebuild Indexes' },
  'debug.actions.reindexDesc': { ar: 'إعادة فهرسة جداول قاعدة البيانات', en: 'Re-index database tables' },
  'debug.actions.reindexDone': { ar: 'تمت إعادة بناء الفهارس', en: 'Indexes rebuilt' },
  'debug.actions.health': { ar: 'فحص صحة النظام', en: 'Health Check' },
  'debug.actions.healthDesc': { ar: 'قياس مباشر لنقطة /api/health', en: 'Live probe of /api/health' },
  'debug.actions.healthOk': { ar: 'النظام سليم — زمن الاستجابة', en: 'System healthy — latency' },
  'debug.actions.healthFail': { ar: 'فشل فحص الصحة — لا استجابة', en: 'Health check failed — no response' },
  'debug.actions.download': { ar: 'تنزيل السجل', en: 'Download Log' },
  'debug.actions.downloadDesc': { ar: 'تصدير سجل وحدة التحكم', en: 'Export console log' },
  'debug.actions.downloadDone': { ar: 'تم تنزيل ملف السجل', en: 'Log file downloaded' },
  'debug.actions.maintenance': { ar: 'وضع الصيانة', en: 'Maintenance Mode' },
  'debug.actions.maintenanceDesc': { ar: 'حجب الوصول لغير المسؤولين', en: 'Block non-admin access' },
  'debug.actions.maintenanceOn': { ar: 'تم تفعيل وضع الصيانة', en: 'Maintenance mode enabled' },
  'debug.actions.maintenanceOff': { ar: 'تم إيقاف وضع الصيانة', en: 'Maintenance mode disabled' },
  'debug.actions.running': { ar: 'جارٍ التنفيذ…', en: 'Running…' },
  'debug.actions.on': { ar: 'مُفعّل', en: 'ON' },
  'debug.actions.off': { ar: 'مُعطّل', en: 'OFF' },
  'debug.actions.dangerZone': { ar: 'منطقة الخطر', en: 'Danger Zone' },
  'debug.actions.restart': { ar: 'إعادة تشغيل الخادم', en: 'Restart Server' },
  'debug.actions.restartDesc': { ar: 'إعادة تشغيل عملية الخادم (محاكاة)', en: 'Reboot server process (simulated)' },
  'debug.actions.restartDone': { ar: 'تم جدولة إعادة التشغيل', en: 'Restart scheduled' },
})
