/**
 * qapture config — generated by `qapture init`, filled in for GEO_ERP.
 *
 * Re-run `qapture init --force` only if you want to regenerate from scratch
 * (edits below WILL be overwritten with --force).
 *
 * Schema reference: https://github.com/mohammed-farhood/qapture#qaconfig
 *
 * Auto-detected stack:
 *   • Vite
 *   • React
 *   • Tailwind CSS
 *   • TypeScript
 *   • Express + better-sqlite3 (API)
 */

import type { QaConfig } from 'qapture2';

const config: QaConfig = {
  namespace: 'geo-erp-system',

  theme: {
    primary: '#1a5f7a',
    primaryDark: '#134b61',
    accent: '#e8a838',
    accentDark: '#cf9220',
    sage: '#64748b',
    cream: '#f8fafc',
    mauve: '#2d9cdb',
    surface: '#ffffff',
    ink: '#1e293b',
  },

  brand: {
    label: 'Alkebis GEO ERP — QA',
  },

  rtl: true,

  loginField: {
    en: 'Username',
    ar: 'اسم المستخدم',
  },

  // No auth in this demo — the header's role switcher is cosmetic only and
  // does not gate any data or API routes. Nothing to seed here.
  credentials: [],

  journey: [
    {
      id: 'demo-tester',
      color: '#1a5f7a',
      role: { en: 'Demo tester', ar: 'مختبر العرض التجريبي' },
      steps: [
        {
          path: '/dashboard',
          risk: 'green',
          riskWhy: 'Read-only, live-computed KPIs and charts.',
          what: {
            en: 'Check KPIs, charts, and recent activity render correctly across companies.',
            ar: 'تحقق من ظهور المؤشرات والرسوم البيانية والنشاط الأخير بشكل صحيح لجميع الشركات.',
          },
        },
        {
          path: '/accounting',
          risk: 'red',
          riskWhy:
            'Journal entries must balance (Σdebit = Σcredit) — server rejects unbalanced entries. Chart of accounts / companies / projects are treated as real, protected data.',
          what: {
            en: 'Create a journal entry, confirm the server rejects an unbalanced one, and browse the chart of accounts and ledgers.',
            ar: 'أنشئ قيدًا محاسبيًا، وتأكد من رفض الخادم لأي قيد غير متوازن، وتصفح دليل الحسابات ودفتر الأستاذ.',
          },
        },
        {
          path: '/warehouse',
          risk: 'red',
          riskWhy:
            'Transactions actually move stock and are audit-logged; the 14-category taxonomy is a single source of truth.',
          what: {
            en: 'Browse items by category, create a stock transaction (in / out / transfer), and confirm quantities update and the event appears in the activity feed.',
            ar: 'تصفح المواد حسب التصنيف، وأنشئ حركة مخزون (إدخال / إخراج / تحويل)، وتأكد من تحديث الكميات وظهور الحركة في سجل النشاط.',
          },
        },
        {
          path: '/fleet',
          risk: 'amber',
          riskWhy: 'Vehicle add/edit writes real records + audit log entries (docs, costs, map points).',
          what: {
            en: 'Add a vehicle using the full form (map point + documents) and confirm it appears in the company roster and vehicle accounting tree.',
            ar: 'أضف مركبة باستخدام النموذج الكامل (نقطة الخريطة + المستندات) وتأكد من ظهورها في قائمة الشركة وشجرة حسابات المركبات.',
          },
        },
        {
          path: '/companies',
          risk: 'green',
          riskWhy: 'Locked module (see UNLOCKED_MODULES in src/config/nav.ts) — must render LockedPage, never crash.',
          what: {
            en: 'Confirm this module shows the lock screen (not a crash or blank page) — it is not yet unlocked for the demo.',
            ar: 'تأكد من ظهور شاشة القفل لهذه الوحدة (وليس عطلاً أو صفحة فارغة) — لم يتم فتحها بعد في هذا العرض التجريبي.',
          },
        },
        {
          path: '/projects',
          risk: 'green',
          riskWhy: 'Locked module (see UNLOCKED_MODULES in src/config/nav.ts) — must render LockedPage, never crash.',
          what: {
            en: 'Confirm this module shows the lock screen (not a crash or blank page) — it is not yet unlocked for the demo.',
            ar: 'تأكد من ظهور شاشة القفل لهذه الوحدة (وليس عطلاً أو صفحة فارغة) — لم يتم فتحها بعد في هذا العرض التجريبي.',
          },
        },
        {
          path: '/hr',
          risk: 'green',
          riskWhy: 'Locked module (see UNLOCKED_MODULES in src/config/nav.ts) — must render LockedPage, never crash.',
          what: {
            en: 'Confirm this module shows the lock screen (not a crash or blank page) — it is not yet unlocked for the demo.',
            ar: 'تأكد من ظهور شاشة القفل لهذه الوحدة (وليس عطلاً أو صفحة فارغة) — لم يتم فتحها بعد في هذا العرض التجريبي.',
          },
        },
        {
          path: '/archive',
          risk: 'green',
          riskWhy: 'Locked module (see UNLOCKED_MODULES in src/config/nav.ts) — must render LockedPage, never crash.',
          what: {
            en: 'Confirm this module shows the lock screen (not a crash or blank page) — it is not yet unlocked for the demo.',
            ar: 'تأكد من ظهور شاشة القفل لهذه الوحدة (وليس عطلاً أو صفحة فارغة) — لم يتم فتحها بعد في هذا العرض التجريبي.',
          },
        },
        {
          path: '/logs',
          risk: 'green',
          riskWhy: 'Locked module (see UNLOCKED_MODULES in src/config/nav.ts) — must render LockedPage, never crash.',
          what: {
            en: 'Confirm this module shows the lock screen (not a crash or blank page) — it is not yet unlocked for the demo.',
            ar: 'تأكد من ظهور شاشة القفل لهذه الوحدة (وليس عطلاً أو صفحة فارغة) — لم يتم فتحها بعد في هذا العرض التجريبي.',
          },
        },
        {
          path: '/debug',
          risk: 'green',
          riskWhy: 'Locked module (see UNLOCKED_MODULES in src/config/nav.ts) — must render LockedPage, never crash.',
          what: {
            en: 'Confirm this module shows the lock screen (not a crash or blank page) — it is not yet unlocked for the demo.',
            ar: 'تأكد من ظهور شاشة القفل لهذه الوحدة (وليس عطلاً أو صفحة فارغة) — لم يتم فتحها بعد في هذا العرض التجريبي.',
          },
        },
      ],
    },
  ],

  /**
   * preamble — read by your AI coding agent (Claude Code, Cursor, Windsurf, etc.)
   * when it processes a qa-notes-*.zip export. Kept in sync with qa.preamble.md.
   */
  preamble: {
    projectName: 'GEO ERP System (Alkebis / مجموعة القبس)',
    oneLiner:
      'Arabic-first (RTL, AR/EN toggle) demo ERP for an Iraqi construction/engineering group (1 parent + 11 subsidiaries). No auth, cosmetic role switcher — but operations are real: data persists, journals must balance, stock moves, reports compute live, every write is audit-logged.',
    stack:
      'TypeScript end-to-end, Node run via tsx (no compile step for the server). Frontend: React 18 + Vite 5 + Tailwind CSS 3 (RTL) + React Router 6 + Recharts + lucide-react. Backend: Express 4 + better-sqlite3 (server/data/erp.db, gitignored); exceljs for fleet Excel import. `@` path alias → ./src.',
    runCommands:
      'npm install && npm run seed && npm run dev — API on :4000, Vite dev server on :5173 (proxies /api → 4000), both together via concurrently. npm run seed:fleet / npm run seed:warehouse reseed just those modules additively. npm run typecheck for the TS build.',
    conventions:
      'Special API routers (dashboard, accounting, reports, warehouse, fleet, vehicleAccounting, vehicleDocs) mount BEFORE the generic /api/:resource CRUD router in server/index.ts — order matters. All UI text is bilingual via src/i18n/strings.ts (+ per-module strings.ts) — add both AR and EN keys for any new copy. Each module lives under src/modules/<name>/ and exports routes.tsx. Locked modules keep their URL paths but render LockedPage (gate() in src/App.tsx, isModuleLocked() in src/config/nav.ts).',
    invariants:
      'Journal entries must balance (Σdebit = Σcredit) — server rejects unbalanced entries. Warehouse transactions must actually move stock and be audit-logged (server/lib/eventLog.ts). Companies/projects/chart-of-accounts are real data — never delete, overwrite, or reseed server/data in a way that loses them. Locked modules (UNLOCKED_MODULES in src/config/nav.ts) must never crash — they always render LockedPage.',
    verifySteps:
      'npm run dev → open http://localhost:5173 → no login needed → exercise the unlocked modules (dashboard, accounting, warehouse, fleet) end to end → npm run typecheck must stay clean.',
    additionalContext:
      'Active demo build, not production — but the DB and business logic are real (SQLite, live-computed reports, real audit log), so treat data-integrity bugs (unbalanced journals, stock drift) as high severity even though there is no real auth or real users. Do NOT read or reseed server/data (gitignored, holds the live demo DB) — see the "Do NOT read" section of CLAUDE.md for other excluded paths (node_modules, dist, large binaries).',
  },
};

export default config;
